import type { Player } from './gameData';

/**
 * Segunda leva do catálogo de jogadores de grandes ligas.
 *
 * O módulo fica separado do catálogo principal para facilitar auditorias e
 * futuras atualizações. Variantes de clube recebem IDs próprios: uma carta de
 * Di María no Benfica, por exemplo, não substitui as versões já existentes.
 */
type CatalogProfile = Omit<Player, 'rarity' | 'traits'>;

function rarityForOverall(overall: number): Exclude<Player['rarity'], 'unique'> {
  if (overall <= 74) return 'bronze';
  if (overall <= 79) return 'silver';
  if (overall <= 87) return 'gold';
  if (overall <= 93) return 'legendary';
  return 'immortal';
}

const catalogPlayer = (player: CatalogProfile): Player => ({
  ...player,
  rarity: rarityForOverall(player.overall),
  traits: [],
});

export const MAJOR_LEAGUE_CATALOG_EXPANSION: Player[] = [
  // Premier League — 29 cartas
  catalogPlayer({ id: 'palmer_chelsea', shortName: 'Palmer', fullName: 'Cole Palmer', position: 'CAM', secondaryPositions: ['RW', 'ST'], nation: 'Inglaterra', club: 'Chelsea', season: '2025/26', overall: 89, pace: 78, shooting: 86, passing: 90, dribbling: 88, defending: 33, physical: 67, composure: 92, vision: 94 }),
  catalogPlayer({ id: 'caicedo_chelsea', shortName: 'Caicedo', fullName: 'Moisés Caicedo', position: 'CDM', secondaryPositions: ['CM'], nation: 'Equador', club: 'Chelsea', season: '2025/26', overall: 86, pace: 78, shooting: 40, passing: 78, dribbling: 71, defending: 88, physical: 83, composure: 82, vision: 75 }),
  catalogPlayer({ id: 'enzo_chelsea', shortName: 'Enzo Fernández', fullName: 'Enzo Fernández', position: 'CM', secondaryPositions: ['CDM', 'CAM'], nation: 'Argentina', club: 'Chelsea', season: '2025/26', overall: 86, pace: 66, shooting: 64, passing: 89, dribbling: 78, defending: 64, physical: 68, composure: 88, vision: 91 }),
  catalogPlayer({ id: 'gusto_chelsea', shortName: 'Gusto', fullName: 'Malo Gusto', position: 'RB', secondaryPositions: ['RWB'], nation: 'França', club: 'Chelsea', season: '2025/26', overall: 82, pace: 88, shooting: 38, passing: 74, dribbling: 80, defending: 70, physical: 69, composure: 73, vision: 64 }),
  catalogPlayer({ id: 'colwill_chelsea', shortName: 'Colwill', fullName: 'Levi Colwill', position: 'CB', secondaryPositions: ['LB'], nation: 'Inglaterra', club: 'Chelsea', season: '2025/26', overall: 83, pace: 73, shooting: 32, passing: 76, dribbling: 57, defending: 82, physical: 78, composure: 80, vision: 58 }),
  catalogPlayer({ id: 'nicolas_jackson_chelsea', shortName: 'N. Jackson', fullName: 'Nicolas Jackson', position: 'ST', secondaryPositions: ['LW'], nation: 'Senegal', club: 'Chelsea', season: '2025/26', overall: 83, pace: 91, shooting: 78, passing: 58, dribbling: 79, defending: 27, physical: 77, composure: 73, vision: 53 }),
  catalogPlayer({ id: 'pedro_neto_chelsea', shortName: 'Pedro Neto', fullName: 'Pedro Neto', position: 'RW', secondaryPositions: ['LW'], nation: 'Portugal', club: 'Chelsea', season: '2025/26', overall: 84, pace: 93, shooting: 72, passing: 77, dribbling: 87, defending: 30, physical: 62, composure: 76, vision: 78 }),
  catalogPlayer({ id: 'cucurella_chelsea', shortName: 'Cucurella', fullName: 'Marc Cucurella', position: 'LB', secondaryPositions: ['LWB', 'CM'], nation: 'Espanha', club: 'Chelsea', season: '2025/26', overall: 84, pace: 81, shooting: 37, passing: 78, dribbling: 79, defending: 76, physical: 74, composure: 78, vision: 69 }),
  catalogPlayer({ id: 'mainoo_united', shortName: 'Mainoo', fullName: 'Kobbie Mainoo', position: 'CM', secondaryPositions: ['CDM'], nation: 'Inglaterra', club: 'Manchester United', season: '2025/26', overall: 82, pace: 69, shooting: 56, passing: 78, dribbling: 83, defending: 69, physical: 72, composure: 82, vision: 76 }),
  catalogPlayer({ id: 'yoro_united', shortName: 'Yoro', fullName: 'Leny Yoro', position: 'CB', nation: 'França', club: 'Manchester United', season: '2025/26', overall: 82, pace: 81, shooting: 28, passing: 67, dribbling: 50, defending: 80, physical: 76, composure: 74, vision: 45 }),
  catalogPlayer({ id: 'hojlund_united', shortName: 'Højlund', fullName: 'Rasmus Højlund', position: 'ST', nation: 'Dinamarca', club: 'Manchester United', season: '2025/26', overall: 82, pace: 87, shooting: 79, passing: 49, dribbling: 72, defending: 26, physical: 82, composure: 74, vision: 46 }),
  catalogPlayer({ id: 'amad_united', shortName: 'Amad', fullName: 'Amad Diallo', position: 'RW', secondaryPositions: ['CAM', 'RM'], nation: 'Costa do Marfim', club: 'Manchester United', season: '2025/26', overall: 82, pace: 85, shooting: 69, passing: 78, dribbling: 87, defending: 31, physical: 57, composure: 76, vision: 79 }),
  catalogPlayer({ id: 'garnacho_united', basePlayerId: 'garnacho', historicalPlayerId: 'garnacho_united', shortName: 'Garnacho', fullName: 'Alejandro Garnacho Ferreyra', position: 'LW', secondaryPositions: ['RW'], nation: 'Argentina', club: 'Manchester United', season: '2025/26', overall: 84, pace: 93, shooting: 74, passing: 68, dribbling: 87, defending: 28, physical: 64, composure: 77, vision: 65 }),
  catalogPlayer({ id: 'maddison_tottenham', shortName: 'Maddison', fullName: 'James Maddison', position: 'CAM', secondaryPositions: ['CM', 'LW'], nation: 'Inglaterra', club: 'Tottenham', season: '2025/26', overall: 85, pace: 70, shooting: 77, passing: 89, dribbling: 84, defending: 30, physical: 58, composure: 84, vision: 93 }),
  catalogPlayer({ id: 'romero_tottenham', shortName: 'Romero', fullName: 'Cristian Romero', position: 'CB', nation: 'Argentina', club: 'Tottenham', season: '2025/26', overall: 86, pace: 77, shooting: 38, passing: 75, dribbling: 58, defending: 89, physical: 82, composure: 78, vision: 55 }),
  catalogPlayer({ id: 'udogie_tottenham', shortName: 'Udogie', fullName: 'Destiny Udogie', position: 'LB', secondaryPositions: ['LWB'], nation: 'Itália', club: 'Tottenham', season: '2025/26', overall: 83, pace: 89, shooting: 44, passing: 73, dribbling: 80, defending: 68, physical: 77, composure: 73, vision: 62 }),
  catalogPlayer({ id: 'kulusevski_tottenham', shortName: 'Kulusevski', fullName: 'Dejan Kulusevski', position: 'RW', secondaryPositions: ['RM', 'CAM'], nation: 'Suécia', club: 'Tottenham', season: '2025/26', overall: 84, pace: 77, shooting: 70, passing: 84, dribbling: 82, defending: 35, physical: 77, composure: 79, vision: 86 }),
  catalogPlayer({ id: 'solanke_tottenham', shortName: 'Solanke', fullName: 'Dominic Solanke', position: 'ST', nation: 'Inglaterra', club: 'Tottenham', season: '2025/26', overall: 84, pace: 78, shooting: 82, passing: 61, dribbling: 73, defending: 28, physical: 81, composure: 80, vision: 53 }),
  catalogPlayer({ id: 'bruno_guimaraes_newcastle', shortName: 'Bruno G.', fullName: 'Bruno Guimarães', position: 'CM', secondaryPositions: ['CDM'], nation: 'Brasil', club: 'Newcastle', season: '2025/26', overall: 86, pace: 67, shooting: 64, passing: 86, dribbling: 82, defending: 78, physical: 78, composure: 87, vision: 86 }),
  catalogPlayer({ id: 'tonali_newcastle', shortName: 'Tonali', fullName: 'Sandro Tonali', position: 'CM', secondaryPositions: ['CDM'], nation: 'Itália', club: 'Newcastle', season: '2025/26', overall: 85, pace: 76, shooting: 54, passing: 85, dribbling: 76, defending: 76, physical: 78, composure: 82, vision: 84 }),
  catalogPlayer({ id: 'gordon_newcastle', shortName: 'Gordon', fullName: 'Anthony Gordon', position: 'LW', secondaryPositions: ['ST', 'RW'], nation: 'Inglaterra', club: 'Newcastle', season: '2025/26', overall: 84, pace: 92, shooting: 75, passing: 69, dribbling: 84, defending: 28, physical: 67, composure: 76, vision: 61 }),
  catalogPlayer({ id: 'watkins_villa', shortName: 'Watkins', fullName: 'Ollie Watkins', position: 'ST', secondaryPositions: ['LW'], nation: 'Inglaterra', club: 'Aston Villa', season: '2025/26', overall: 85, pace: 89, shooting: 83, passing: 61, dribbling: 77, defending: 24, physical: 80, composure: 80, vision: 55 }),
  catalogPlayer({ id: 'morgan_rogers_villa', shortName: 'Rogers', fullName: 'Morgan Rogers', position: 'CAM', secondaryPositions: ['LW', 'ST'], nation: 'Inglaterra', club: 'Aston Villa', season: '2025/26', overall: 84, pace: 84, shooting: 73, passing: 73, dribbling: 86, defending: 30, physical: 76, composure: 78, vision: 72 }),
  catalogPlayer({ id: 'pau_torres_villa', shortName: 'Pau Torres', fullName: 'Pau Torres', position: 'CB', nation: 'Espanha', club: 'Aston Villa', season: '2025/26', overall: 84, pace: 69, shooting: 35, passing: 84, dribbling: 63, defending: 82, physical: 72, composure: 84, vision: 63 }),
  catalogPlayer({ id: 'konsa_villa', shortName: 'Konsa', fullName: 'Ezri Konsa', position: 'CB', secondaryPositions: ['RB'], nation: 'Inglaterra', club: 'Aston Villa', season: '2025/26', overall: 83, pace: 76, shooting: 27, passing: 65, dribbling: 45, defending: 84, physical: 78, composure: 77, vision: 47 }),
  catalogPlayer({ id: 'tielemans_villa', shortName: 'Tielemans', fullName: 'Youri Tielemans', position: 'CM', secondaryPositions: ['CDM', 'CAM'], nation: 'Bélgica', club: 'Aston Villa', season: '2025/26', overall: 84, pace: 58, shooting: 68, passing: 86, dribbling: 77, defending: 54, physical: 67, composure: 86, vision: 88 }),
  catalogPlayer({ id: 'isak_newcastle', basePlayerId: 'isak', historicalPlayerId: 'isak_newcastle', shortName: 'Isak', fullName: 'Alexander Isak', position: 'ST', secondaryPositions: ['LW'], nation: 'Suécia', club: 'Newcastle', season: '2024/25', overall: 88, pace: 89, shooting: 88, passing: 73, dribbling: 86, defending: 29, physical: 74, composure: 86, vision: 69 }),
  catalogPlayer({ id: 'bowen_west_ham', shortName: 'Bowen', fullName: 'Jarrod Bowen', position: 'RW', secondaryPositions: ['ST', 'RM'], nation: 'Inglaterra', club: 'West Ham', season: '2025/26', overall: 84, pace: 85, shooting: 78, passing: 67, dribbling: 80, defending: 34, physical: 68, composure: 79, vision: 60 }),
  catalogPlayer({ id: 'kudus_west_ham', shortName: 'Kudus', fullName: 'Mohammed Kudus', position: 'CAM', secondaryPositions: ['RW', 'CM'], nation: 'Gana', club: 'West Ham', season: '2025/26', overall: 84, pace: 89, shooting: 72, passing: 72, dribbling: 90, defending: 30, physical: 76, composure: 78, vision: 67 }),

  // La Liga — 14 cartas
  catalogPlayer({ id: 'olmo_barcelona', shortName: 'Dani Olmo', fullName: 'Dani Olmo Carvajal', position: 'CAM', secondaryPositions: ['CM', 'LW'], nation: 'Espanha', club: 'Barcelona', season: '2025/26', overall: 86, pace: 78, shooting: 78, passing: 87, dribbling: 87, defending: 31, physical: 63, composure: 84, vision: 89 }),
  catalogPlayer({ id: 'ferran_barcelona', shortName: 'Ferran', fullName: 'Ferran Torres García', position: 'RW', secondaryPositions: ['LW', 'ST'], nation: 'Espanha', club: 'Barcelona', season: '2025/26', overall: 83, pace: 86, shooting: 78, passing: 64, dribbling: 77, defending: 29, physical: 65, composure: 77, vision: 59 }),
  catalogPlayer({ id: 'alvarez_atletico', shortName: 'Julián Álvarez', fullName: 'Julián Álvarez', position: 'ST', secondaryPositions: ['CAM'], nation: 'Argentina', club: 'Atlético Madrid', season: '2025/26', overall: 88, pace: 86, shooting: 86, passing: 76, dribbling: 85, defending: 31, physical: 73, composure: 88, vision: 76 }),
  catalogPlayer({ id: 'de_paul_atletico', shortName: 'De Paul', fullName: 'Rodrigo De Paul', position: 'CM', secondaryPositions: ['CDM', 'CAM'], nation: 'Argentina', club: 'Atlético Madrid', season: '2025/26', overall: 85, pace: 70, shooting: 59, passing: 87, dribbling: 79, defending: 57, physical: 72, composure: 85, vision: 88 }),
  catalogPlayer({ id: 'molina_atletico', shortName: 'Molina', fullName: 'Nahuel Molina', position: 'RB', secondaryPositions: ['RWB'], nation: 'Argentina', club: 'Atlético Madrid', season: '2025/26', overall: 83, pace: 85, shooting: 38, passing: 72, dribbling: 76, defending: 73, physical: 73, composure: 75, vision: 59 }),
  catalogPlayer({ id: 'le_normand_atletico', shortName: 'Le Normand', fullName: 'Robin Le Normand', position: 'CB', nation: 'Espanha', club: 'Atlético Madrid', season: '2025/26', overall: 84, pace: 61, shooting: 31, passing: 72, dribbling: 47, defending: 87, physical: 80, composure: 82, vision: 48 }),
  catalogPlayer({ id: 'oyarzabal_sociedad', shortName: 'Oyarzabal', fullName: 'Mikel Oyarzabal', position: 'LW', secondaryPositions: ['ST', 'CAM'], nation: 'Espanha', club: 'Real Sociedad', season: '2025/26', overall: 84, pace: 73, shooting: 82, passing: 72, dribbling: 79, defending: 26, physical: 63, composure: 86, vision: 72 }),
  catalogPlayer({ id: 'kubo_sociedad', shortName: 'Kubo', fullName: 'Takefusa Kubo', position: 'RW', secondaryPositions: ['CAM', 'LW'], nation: 'Japão', club: 'Real Sociedad', season: '2025/26', overall: 84, pace: 87, shooting: 64, passing: 79, dribbling: 90, defending: 27, physical: 55, composure: 77, vision: 84 }),
  catalogPlayer({ id: 'isco_betis', shortName: 'Isco', fullName: 'Francisco Román Alarcón Suárez', position: 'CAM', secondaryPositions: ['CM'], nation: 'Espanha', club: 'Real Betis', season: '2025/26', overall: 84, pace: 58, shooting: 72, passing: 89, dribbling: 91, defending: 26, physical: 57, composure: 88, vision: 94 }),
  catalogPlayer({ id: 'ayoze_villarreal', shortName: 'Ayoze', fullName: 'Ayoze Pérez', position: 'ST', secondaryPositions: ['LW', 'CAM'], nation: 'Espanha', club: 'Villarreal', season: '2025/26', overall: 83, pace: 78, shooting: 79, passing: 67, dribbling: 80, defending: 25, physical: 58, composure: 83, vision: 65 }),
  catalogPlayer({ id: 'parejo_villarreal', shortName: 'Parejo', fullName: 'Daniel Parejo Muñoz', position: 'CM', secondaryPositions: ['CDM'], nation: 'Espanha', club: 'Villarreal', season: '2025/26', overall: 82, pace: 42, shooting: 65, passing: 93, dribbling: 70, defending: 42, physical: 47, composure: 90, vision: 95 }),
  catalogPlayer({ id: 'yeremy_pino_villarreal', shortName: 'Yeremy Pino', fullName: 'Yeremy Pino Santos', position: 'RW', secondaryPositions: ['LW', 'CAM'], nation: 'Espanha', club: 'Villarreal', season: '2025/26', overall: 82, pace: 86, shooting: 62, passing: 69, dribbling: 82, defending: 27, physical: 58, composure: 73, vision: 64 }),
  catalogPlayer({ id: 'alex_baena_villarreal', shortName: 'Álex Baena', fullName: 'Alejandro Baena Rodríguez', position: 'CAM', secondaryPositions: ['LM', 'CM'], nation: 'Espanha', club: 'Villarreal', season: '2025/26', overall: 84, pace: 73, shooting: 63, passing: 87, dribbling: 83, defending: 29, physical: 54, composure: 79, vision: 91 }),
  catalogPlayer({ id: 'mamardashvili_valencia', shortName: 'Mamardashvili', fullName: 'Giorgi Mamardashvili', position: 'GK', nation: 'Geórgia', club: 'Valencia', season: '2024/25', overall: 85, pace: 43, shooting: 18, passing: 43, dribbling: 22, defending: 90, physical: 83, composure: 79, vision: 74 }),

  // Serie A — 16 cartas
  catalogPlayer({ id: 'maignan_milan', shortName: 'Maignan', fullName: 'Mike Maignan', position: 'GK', nation: 'França', club: 'Milan', season: '2025/26', overall: 87, pace: 48, shooting: 20, passing: 57, dribbling: 28, defending: 91, physical: 80, composure: 86, vision: 84 }),
  catalogPlayer({ id: 'pulisic_milan', shortName: 'Pulisic', fullName: 'Christian Pulisic', position: 'RW', secondaryPositions: ['LW', 'CAM'], nation: 'Estados Unidos', club: 'Milan', season: '2025/26', overall: 85, pace: 89, shooting: 78, passing: 77, dribbling: 86, defending: 30, physical: 61, composure: 80, vision: 77 }),
  catalogPlayer({ id: 'fofana_milan', shortName: 'Fofana', fullName: 'Youssouf Fofana', position: 'CDM', secondaryPositions: ['CM'], nation: 'França', club: 'Milan', season: '2025/26', overall: 83, pace: 76, shooting: 37, passing: 73, dribbling: 66, defending: 82, physical: 83, composure: 77, vision: 62 }),
  catalogPlayer({ id: 'tomori_milan', shortName: 'Tomori', fullName: 'Fikayo Tomori', position: 'CB', secondaryPositions: ['RB'], nation: 'Inglaterra', club: 'Milan', season: '2025/26', overall: 83, pace: 88, shooting: 26, passing: 57, dribbling: 45, defending: 82, physical: 78, composure: 70, vision: 43 }),
  catalogPlayer({ id: 'bastoni_inter', shortName: 'Bastoni', fullName: 'Alessandro Bastoni', position: 'CB', secondaryPositions: ['LB'], nation: 'Itália', club: 'Inter Milan', season: '2025/26', overall: 87, pace: 72, shooting: 34, passing: 86, dribbling: 63, defending: 87, physical: 78, composure: 87, vision: 71 }),
  catalogPlayer({ id: 'dimarco_inter', shortName: 'Dimarco', fullName: 'Federico Dimarco', position: 'LB', secondaryPositions: ['LWB', 'LM'], nation: 'Itália', club: 'Inter Milan', season: '2025/26', overall: 85, pace: 84, shooting: 65, passing: 87, dribbling: 82, defending: 69, physical: 66, composure: 77, vision: 84 }),
  catalogPlayer({ id: 'bremer_juventus', shortName: 'Bremer', fullName: 'Gleison Bremer', position: 'CB', nation: 'Brasil', club: 'Juventus', season: '2025/26', overall: 86, pace: 79, shooting: 31, passing: 56, dribbling: 41, defending: 90, physical: 87, composure: 79, vision: 41 }),
  catalogPlayer({ id: 'yildiz_juventus', shortName: 'Yıldız', fullName: 'Kenan Yıldız', position: 'CAM', secondaryPositions: ['LW', 'ST'], nation: 'Turquia', club: 'Juventus', season: '2025/26', overall: 84, pace: 83, shooting: 74, passing: 79, dribbling: 87, defending: 27, physical: 63, composure: 79, vision: 78 }),
  catalogPlayer({ id: 'cambiaso_juventus', shortName: 'Cambiaso', fullName: 'Andrea Cambiaso', position: 'LB', secondaryPositions: ['RB', 'RM'], nation: 'Itália', club: 'Juventus', season: '2025/26', overall: 83, pace: 81, shooting: 45, passing: 76, dribbling: 80, defending: 72, physical: 70, composure: 76, vision: 66 }),
  catalogPlayer({ id: 'mctominay_napoli', shortName: 'McTominay', fullName: 'Scott McTominay', position: 'CM', secondaryPositions: ['CDM', 'ST'], nation: 'Escócia', club: 'Napoli', season: '2025/26', overall: 85, pace: 72, shooting: 75, passing: 67, dribbling: 66, defending: 73, physical: 88, composure: 79, vision: 59 }),
  catalogPlayer({ id: 'lobotka_napoli', shortName: 'Lobotka', fullName: 'Stanislav Lobotka', position: 'CDM', secondaryPositions: ['CM'], nation: 'Eslováquia', club: 'Napoli', season: '2025/26', overall: 84, pace: 70, shooting: 27, passing: 88, dribbling: 87, defending: 75, physical: 55, composure: 88, vision: 87 }),
  catalogPlayer({ id: 'di_lorenzo_napoli', shortName: 'Di Lorenzo', fullName: 'Giovanni Di Lorenzo', position: 'RB', secondaryPositions: ['CB', 'LB'], nation: 'Itália', club: 'Napoli', season: '2025/26', overall: 84, pace: 78, shooting: 39, passing: 76, dribbling: 72, defending: 81, physical: 78, composure: 81, vision: 66 }),
  catalogPlayer({ id: 'lookman_atalanta', shortName: 'Lookman', fullName: 'Ademola Lookman', position: 'LW', secondaryPositions: ['ST', 'RW'], nation: 'Nigéria', club: 'Atalanta', season: '2025/26', overall: 86, pace: 92, shooting: 82, passing: 73, dribbling: 87, defending: 28, physical: 70, composure: 82, vision: 70 }),
  catalogPlayer({ id: 'ederson_atalanta', shortName: 'Éderson', fullName: 'Éderson José dos Santos Lourenço da Silva', position: 'CM', secondaryPositions: ['CDM'], nation: 'Brasil', club: 'Atalanta', season: '2025/26', overall: 84, pace: 79, shooting: 54, passing: 75, dribbling: 78, defending: 78, physical: 83, composure: 79, vision: 65 }),
  catalogPlayer({ id: 'retegui_atalanta', shortName: 'Retegui', fullName: 'Mateo Retegui', position: 'ST', nation: 'Itália', club: 'Atalanta', season: '2025/26', overall: 84, pace: 77, shooting: 84, passing: 51, dribbling: 67, defending: 27, physical: 83, composure: 79, vision: 46 }),
  catalogPlayer({ id: 'soule_roma', shortName: 'Soulé', fullName: 'Matías Soulé Malvano', position: 'RW', secondaryPositions: ['CAM', 'ST'], nation: 'Argentina', club: 'Roma', season: '2025/26', overall: 82, pace: 78, shooting: 68, passing: 76, dribbling: 86, defending: 27, physical: 54, composure: 78, vision: 80 }),

  // Bundesliga — 11 cartas
  catalogPlayer({ id: 'frimpong_leverkusen', basePlayerId: 'frimpong', historicalPlayerId: 'frimpong_leverkusen', shortName: 'Frimpong', fullName: 'Jeremie Frimpong', position: 'RWB', secondaryPositions: ['RB', 'RW'], nation: 'Holanda', club: 'Bayer Leverkusen', season: '2024/25', overall: 86, pace: 96, shooting: 70, passing: 76, dribbling: 89, defending: 51, physical: 65, composure: 77, vision: 70 }),
  catalogPlayer({ id: 'schick_leverkusen', shortName: 'Schick', fullName: 'Patrik Schick', position: 'ST', nation: 'República Tcheca', club: 'Bayer Leverkusen', season: '2025/26', overall: 84, pace: 73, shooting: 86, passing: 58, dribbling: 74, defending: 25, physical: 79, composure: 84, vision: 55 }),
  catalogPlayer({ id: 'boniface_leverkusen', shortName: 'Boniface', fullName: 'Victor Boniface', position: 'ST', nation: 'Nigéria', club: 'Bayer Leverkusen', season: '2025/26', overall: 84, pace: 83, shooting: 82, passing: 55, dribbling: 76, defending: 24, physical: 87, composure: 74, vision: 49 }),
  catalogPlayer({ id: 'brandt_dortmund', shortName: 'Brandt', fullName: 'Julian Brandt', position: 'CAM', secondaryPositions: ['CM', 'LM'], nation: 'Alemanha', club: 'Borussia Dortmund', season: '2025/26', overall: 84, pace: 72, shooting: 74, passing: 86, dribbling: 84, defending: 28, physical: 58, composure: 78, vision: 91 }),
  catalogPlayer({ id: 'adeyemi_dortmund', shortName: 'Adeyemi', fullName: 'Karim Adeyemi', position: 'LW', secondaryPositions: ['ST', 'RW'], nation: 'Alemanha', club: 'Borussia Dortmund', season: '2025/26', overall: 83, pace: 96, shooting: 72, passing: 53, dribbling: 82, defending: 21, physical: 67, composure: 69, vision: 47 }),
  catalogPlayer({ id: 'schlotterbeck_dortmund', shortName: 'Schlotterbeck', fullName: 'Nico Schlotterbeck', position: 'CB', nation: 'Alemanha', club: 'Borussia Dortmund', season: '2025/26', overall: 85, pace: 78, shooting: 35, passing: 79, dribbling: 54, defending: 84, physical: 80, composure: 79, vision: 57 }),
  catalogPlayer({ id: 'sabitzer_dortmund', basePlayerId: 'm_sabitzer', historicalPlayerId: 'sabitzer_dortmund', shortName: 'Sabitzer', fullName: 'Marcel Sabitzer', position: 'CM', secondaryPositions: ['CDM', 'CAM'], nation: 'Áustria', club: 'Borussia Dortmund', season: '2025/26', overall: 83, pace: 71, shooting: 70, passing: 78, dribbling: 75, defending: 59, physical: 79, composure: 79, vision: 73 }),
  catalogPlayer({ id: 'xavi_simons_leipzig', shortName: 'Xavi Simons', fullName: 'Xavi Simons', position: 'CAM', secondaryPositions: ['LW', 'CM'], nation: 'Holanda', club: 'RB Leipzig', season: '2025/26', overall: 85, pace: 86, shooting: 73, passing: 81, dribbling: 89, defending: 25, physical: 57, composure: 80, vision: 86 }),
  catalogPlayer({ id: 'sesko_leipzig', shortName: 'Šeško', fullName: 'Benjamin Šeško', position: 'ST', nation: 'Eslovênia', club: 'RB Leipzig', season: '2025/26', overall: 84, pace: 87, shooting: 85, passing: 51, dribbling: 73, defending: 24, physical: 82, composure: 74, vision: 50 }),
  catalogPlayer({ id: 'raum_leipzig', shortName: 'Raum', fullName: 'David Raum', position: 'LB', secondaryPositions: ['LWB'], nation: 'Alemanha', club: 'RB Leipzig', season: '2025/26', overall: 83, pace: 86, shooting: 38, passing: 78, dribbling: 78, defending: 67, physical: 75, composure: 73, vision: 69 }),
  catalogPlayer({ id: 'kim_minjae_bayern', shortName: 'Kim Min-jae', fullName: 'Kim Min-jae', position: 'CB', nation: 'Coreia do Sul', club: 'Bayern Munich', season: '2025/26', overall: 85, pace: 81, shooting: 28, passing: 66, dribbling: 47, defending: 88, physical: 86, composure: 76, vision: 45 }),

  // Ligue 1 — 8 cartas
  catalogPlayer({ id: 'barcola_psg', shortName: 'Barcola', fullName: 'Bradley Barcola', position: 'LW', secondaryPositions: ['RW', 'ST'], nation: 'França', club: 'PSG', season: '2025/26', overall: 85, pace: 93, shooting: 76, passing: 73, dribbling: 90, defending: 23, physical: 61, composure: 78, vision: 67 }),
  catalogPlayer({ id: 'kolo_muani_psg', shortName: 'Kolo Muani', fullName: 'Randal Kolo Muani', position: 'ST', secondaryPositions: ['RW'], nation: 'França', club: 'PSG', season: '2025/26', overall: 83, pace: 93, shooting: 77, passing: 62, dribbling: 81, defending: 23, physical: 76, composure: 75, vision: 54 }),
  catalogPlayer({ id: 'greenwood_marseille', shortName: 'Greenwood', fullName: 'Mason Greenwood', position: 'RW', secondaryPositions: ['ST', 'LW'], nation: 'Inglaterra', club: 'Marseille', season: '2025/26', overall: 84, pace: 84, shooting: 85, passing: 68, dribbling: 82, defending: 27, physical: 65, composure: 80, vision: 70 }),
  catalogPlayer({ id: 'rabiot_marseille', shortName: 'Rabiot', fullName: 'Adrien Rabiot', position: 'CM', secondaryPositions: ['CDM'], nation: 'França', club: 'Marseille', season: '2025/26', overall: 84, pace: 78, shooting: 55, passing: 79, dribbling: 77, defending: 67, physical: 83, composure: 80, vision: 75 }),
  catalogPlayer({ id: 'cherki_lyon', basePlayerId: 'cherki', historicalPlayerId: 'cherki_lyon', shortName: 'Cherki', fullName: 'Rayan Cherki', position: 'CAM', secondaryPositions: ['RW', 'LW'], nation: 'França', club: 'Lyon', season: '2024/25', overall: 83, pace: 82, shooting: 70, passing: 87, dribbling: 91, defending: 23, physical: 51, composure: 76, vision: 90 }),
  catalogPlayer({ id: 'mika_biereth_monaco', shortName: 'Biereth', fullName: 'Mika Biereth', position: 'ST', nation: 'Dinamarca', club: 'Monaco', season: '2025/26', overall: 82, pace: 81, shooting: 78, passing: 48, dribbling: 67, defending: 22, physical: 76, composure: 71, vision: 43 }),
  catalogPlayer({ id: 'ben_seghir_monaco', shortName: 'Ben Seghir', fullName: 'Eliesse Ben Seghir', position: 'LW', secondaryPositions: ['CAM', 'RW'], nation: 'Marrocos', club: 'Monaco', season: '2025/26', overall: 82, pace: 86, shooting: 64, passing: 75, dribbling: 87, defending: 24, physical: 54, composure: 75, vision: 77 }),
  catalogPlayer({ id: 'akliouche_monaco', shortName: 'Akliouche', fullName: 'Maghnes Akliouche', position: 'CAM', secondaryPositions: ['RW'], nation: 'França', club: 'Monaco', season: '2025/26', overall: 82, pace: 78, shooting: 61, passing: 79, dribbling: 86, defending: 25, physical: 52, composure: 73, vision: 79 }),

  // Portugal — 8 cartas
  catalogPlayer({ id: 'otamendi_benfica', shortName: 'Otamendi', fullName: 'Nicolás Otamendi', position: 'CB', nation: 'Argentina', club: 'Benfica', season: '2025/26', overall: 82, pace: 52, shooting: 36, passing: 64, dribbling: 39, defending: 84, physical: 79, composure: 82, vision: 45 }),
  catalogPlayer({ id: 'pavlidis_benfica', shortName: 'Pavlidis', fullName: 'Vangelis Pavlidis', position: 'ST', nation: 'Grécia', club: 'Benfica', season: '2025/26', overall: 83, pace: 77, shooting: 84, passing: 50, dribbling: 67, defending: 24, physical: 79, composure: 80, vision: 44 }),
  catalogPlayer({ id: 'aursnes_benfica', shortName: 'Aursnes', fullName: 'Fredrik Aursnes', position: 'CM', secondaryPositions: ['CDM', 'LB'], nation: 'Noruega', club: 'Benfica', season: '2025/26', overall: 83, pace: 73, shooting: 37, passing: 78, dribbling: 73, defending: 73, physical: 75, composure: 81, vision: 68 }),
  catalogPlayer({ id: 'carreras_benfica', shortName: 'Carreras', fullName: 'Álvaro Carreras', position: 'LB', secondaryPositions: ['LWB'], nation: 'Espanha', club: 'Benfica', season: '2025/26', overall: 82, pace: 87, shooting: 33, passing: 72, dribbling: 76, defending: 69, physical: 67, composure: 70, vision: 61 }),
  catalogPlayer({ id: 'diogo_costa_porto', shortName: 'Diogo Costa', fullName: 'Diogo Meireles Costa', position: 'GK', nation: 'Portugal', club: 'Porto', season: '2025/26', overall: 85, pace: 51, shooting: 18, passing: 59, dribbling: 26, defending: 89, physical: 74, composure: 82, vision: 86 }),
  catalogPlayer({ id: 'alan_varela_porto', shortName: 'Alan Varela', fullName: 'Alan Gonzalo Varela', position: 'CDM', secondaryPositions: ['CM'], nation: 'Argentina', club: 'Porto', season: '2025/26', overall: 83, pace: 70, shooting: 30, passing: 77, dribbling: 72, defending: 80, physical: 74, composure: 78, vision: 69 }),
  catalogPlayer({ id: 'francisco_moura_porto', shortName: 'Francisco Moura', fullName: 'Francisco de Jesus Nascimento Moura', position: 'LB', secondaryPositions: ['LM'], nation: 'Portugal', club: 'Porto', season: '2025/26', overall: 81, pace: 83, shooting: 35, passing: 70, dribbling: 75, defending: 66, physical: 69, composure: 68, vision: 56 }),
  catalogPlayer({ id: 'orkun_kokcu_benfica', shortName: 'Kökçü', fullName: 'Orkun Kökçü', position: 'CM', secondaryPositions: ['CAM', 'CDM'], nation: 'Turquia', club: 'Benfica', season: '2025/26', overall: 84, pace: 68, shooting: 68, passing: 88, dribbling: 79, defending: 45, physical: 63, composure: 83, vision: 89 }),

  // Eredivisie — 4 cartas
  catalogPlayer({ id: 'pepi_psv', shortName: 'Pepi', fullName: 'Ricardo Pepi', position: 'ST', nation: 'Estados Unidos', club: 'PSV', season: '2025/26', overall: 82, pace: 77, shooting: 80, passing: 41, dribbling: 60, defending: 22, physical: 73, composure: 74, vision: 38 }),
  catalogPlayer({ id: 'bakayoko_psv', shortName: 'Bakayoko', fullName: 'Johan Bakayoko', position: 'RW', secondaryPositions: ['LW'], nation: 'Bélgica', club: 'PSV', season: '2025/26', overall: 83, pace: 91, shooting: 67, passing: 68, dribbling: 87, defending: 22, physical: 58, composure: 72, vision: 65 }),
  catalogPlayer({ id: 'timber_feyenoord', shortName: 'Timber', fullName: 'Quinten Timber', position: 'CM', secondaryPositions: ['CAM', 'RM'], nation: 'Holanda', club: 'Feyenoord', season: '2025/26', overall: 82, pace: 79, shooting: 64, passing: 72, dribbling: 81, defending: 49, physical: 75, composure: 78, vision: 70 }),
  catalogPlayer({ id: 'hato_ajax', shortName: 'Hato', fullName: 'Jorrel Hato', position: 'CB', secondaryPositions: ['LB'], nation: 'Holanda', club: 'Ajax', season: '2025/26', overall: 81, pace: 78, shooting: 27, passing: 69, dribbling: 53, defending: 77, physical: 62, composure: 72, vision: 50 }),

  // Outras versões relevantes auditadas — 4 cartas
  catalogPlayer({ id: 'konrad_laimer_bayern', shortName: 'Laimer', fullName: 'Konrad Laimer', position: 'CM', secondaryPositions: ['CDM', 'RB'], nation: 'Áustria', club: 'Bayern Munich', season: '2025/26', overall: 84, pace: 84, shooting: 43, passing: 72, dribbling: 72, defending: 77, physical: 82, composure: 78, vision: 64 }),
  catalogPlayer({ id: 'pavlovic_bayern', shortName: 'Pavlović', fullName: 'Aleksandar Pavlović', position: 'CDM', secondaryPositions: ['CM'], nation: 'Alemanha', club: 'Bayern Munich', season: '2025/26', overall: 82, pace: 59, shooting: 36, passing: 80, dribbling: 61, defending: 65, physical: 70, composure: 78, vision: 82 }),
  catalogPlayer({ id: 'eze_arsenal', shortName: 'Eze', fullName: 'Eberechi Eze', position: 'CAM', secondaryPositions: ['LW', 'CM'], nation: 'Inglaterra', club: 'Arsenal', season: '2025/26', overall: 85, pace: 84, shooting: 76, passing: 80, dribbling: 90, defending: 24, physical: 64, composure: 81, vision: 84 }),
  catalogPlayer({ id: 'gyokeres_sporting', basePlayerId: 'gyokeres', historicalPlayerId: 'gyokeres_sporting', shortName: 'Gyökeres', fullName: 'Viktor Gyökeres', position: 'ST', nation: 'Suécia', club: 'Sporting CP', season: '2024/25', overall: 87, pace: 91, shooting: 86, passing: 60, dribbling: 82, defending: 31, physical: 87, composure: 82, vision: 59 }),

];
