import type { Player } from './gameData';

/**
 * Lendas europeias das principais ligas (anos 90 até hoje) ainda ausentes do
 * catálogo, pesquisadas no SortitoutSI. Cada retrato foi verificado
 * individualmente (nome, nacionalidade e data de nascimento reais batendo
 * com o perfil do site) E checado visualmente — mantidos só os que
 * realmente mostram a pessoa na época de jogador, não uma foto atual de
 * comissão técnica/embaixador/comentarista.
 */
export const SORTITOUTSI_EUROPEAN_LEGENDS: Player[] = [
  {
    id: 'yaya_toure', shortName: 'Yaya Touré', fullName: 'Yaya Touré', position: 'CDM', secondaryPositions: ['CM'],
    nation: 'Costa do Marfim', club: 'Manchester City', season: '2013/14', rarity: 'legendary', overall: 89,
    pace: 78, shooting: 68, passing: 87, dribbling: 80,
    defending: 83, physical: 90, composure: 92, vision: 88,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_yaya_toure.webp',
  },
  {
    id: 'trezeguet', shortName: 'David Trezeguet', fullName: 'David Trezeguet', position: 'ST',
    nation: 'França', club: 'Juventus', season: '2002/03', rarity: 'gold', overall: 87,
    pace: 89, shooting: 90, passing: 75, dribbling: 89,
    defending: 44, physical: 87, composure: 91, vision: 82,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_trezeguet.webp',
  },
  {
    id: 'godin', shortName: 'Diego Godín', fullName: 'Diego Godín', position: 'CB',
    nation: 'Uruguai', club: 'Atlético Madrid', season: '2013/14', rarity: 'gold', overall: 87,
    pace: 76, shooting: 37, passing: 78, dribbling: 61,
    defending: 90, physical: 86, composure: 77, vision: 70,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_godin.webp',
  },
  {
    id: 'rakitic', shortName: 'Ivan Rakitić', fullName: 'Ivan Rakitić', position: 'CM',
    nation: 'Croácia', club: 'Barcelona', season: '2014/15', rarity: 'gold', overall: 87,
    pace: 85, shooting: 70, passing: 92, dribbling: 79,
    defending: 70, physical: 85, composure: 83, vision: 88,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_rakitic.webp',
  },
  {
    id: 'kounde', shortName: 'Jules Koundé', fullName: 'Jules Koundé', position: 'CB', secondaryPositions: ['RB'],
    nation: 'França', club: 'Barcelona', season: '2024/25', rarity: 'gold', overall: 85,
    pace: 78, shooting: 45, passing: 70, dribbling: 59,
    defending: 83, physical: 85, composure: 82, vision: 59,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_kounde.webp',
  },
  {
    id: 'thomas_muller', shortName: 'Thomas Müller', fullName: 'Thomas Müller', position: 'CAM', secondaryPositions: ['ST'],
    nation: 'Alemanha', club: 'Bayern Munich', season: '2013/14', rarity: 'legendary', overall: 88,
    pace: 88, shooting: 77, passing: 92, dribbling: 94,
    defending: 48, physical: 76, composure: 88, vision: 97,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_thomas_muller.webp',
  },
  {
    id: 'gotze', shortName: 'Mario Götze', fullName: 'Mario Götze', position: 'CAM',
    nation: 'Alemanha', club: 'Borussia Dortmund', season: '2012/13', rarity: 'gold', overall: 86,
    pace: 80, shooting: 75, passing: 85, dribbling: 93,
    defending: 53, physical: 76, composure: 83, vision: 87,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_gotze.webp',
  },
  {
    id: 'jesus_navas', shortName: 'Jesús Navas', fullName: 'Jesús Navas', position: 'RW', secondaryPositions: ['RB'],
    nation: 'Espanha', club: 'Sevilla', season: '2006/07', rarity: 'gold', overall: 84,
    pace: 88, shooting: 74, passing: 85, dribbling: 93,
    defending: 45, physical: 75, composure: 78, vision: 77,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_jesus_navas.webp',
  },
  {
    id: 'kanoute', shortName: 'Frédéric Kanouté', fullName: 'Frédéric Kanouté', position: 'ST',
    nation: 'Mali', club: 'Sevilla', season: '2006/07', rarity: 'gold', overall: 85,
    pace: 87, shooting: 85, passing: 78, dribbling: 89,
    defending: 41, physical: 81, composure: 82, vision: 70,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_kanoute.webp',
  },
  {
    id: 'aimar', shortName: 'Pablo Aimar', fullName: 'Pablo Aimar', position: 'CAM',
    nation: 'Argentina', club: 'Valencia', season: '2003/04', rarity: 'gold', overall: 86,
    pace: 80, shooting: 75, passing: 85, dribbling: 93,
    defending: 53, physical: 76, composure: 83, vision: 87,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_aimar.webp',
  },
  {
    id: 'gerd_muller', shortName: 'Gerd Müller', fullName: 'Gerd Müller', position: 'ST',
    nation: 'Alemanha', club: 'Bayern Munich', season: '1972/73', rarity: 'immortal', overall: 95,
    pace: 94, shooting: 99, passing: 85, dribbling: 96,
    defending: 48, physical: 88, composure: 99, vision: 88,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_3600230.webp',
  },
  {
    id: 'raul', shortName: 'Raúl', fullName: 'Raúl González', position: 'ST',
    nation: 'Espanha', club: 'Real Madrid', season: '1999/00', rarity: 'legendary', overall: 91,
    pace: 82, shooting: 90, passing: 78, dribbling: 87,
    defending: 35, physical: 75, composure: 93, vision: 85,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_raul.webp',
  },
  {
    id: 'roy_keane', shortName: 'Roy Keane', fullName: 'Roy Keane', position: 'CDM', secondaryPositions: ['CM'],
    nation: 'Irlanda', club: 'Manchester United', season: '1999/00', rarity: 'legendary', overall: 89,
    pace: 72, shooting: 68, passing: 82, dribbling: 78,
    defending: 87, physical: 88, composure: 90, vision: 82,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_keane.webp',
  },
  {
    id: 'hugo_sanchez', shortName: 'Hugo Sánchez', fullName: 'Hugo Sánchez', position: 'ST',
    nation: 'México', club: 'Real Madrid', season: '1989/90', rarity: 'legendary', overall: 90,
    pace: 85, shooting: 92, passing: 72, dribbling: 86,
    defending: 30, physical: 74, composure: 90, vision: 78,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_hugo_sanchez.webp',
  },
  {
    id: 'deco', shortName: 'Deco', fullName: 'Deco', position: 'CAM', secondaryPositions: ['CM'],
    nation: 'Portugal', club: 'FC Porto', season: '2003/04', rarity: 'legendary', overall: 88,
    pace: 74, shooting: 78, passing: 90, dribbling: 89,
    defending: 45, physical: 68, composure: 87, vision: 92,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_deco.webp',
  },
  {
    id: 'fernando_torres', shortName: 'Fernando Torres', fullName: 'Fernando Torres', position: 'ST',
    nation: 'Espanha', club: 'Liverpool', season: '2007/08', rarity: 'legendary', overall: 88,
    pace: 91, shooting: 89, passing: 72, dribbling: 85,
    defending: 30, physical: 76, composure: 85, vision: 74,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_torres.webp',
  },
  {
    id: 'inzaghi', shortName: 'Filippo Inzaghi', fullName: 'Filippo Inzaghi', position: 'ST',
    nation: 'Itália', club: 'Milan', season: '2006/07', rarity: 'gold', overall: 86,
    pace: 82, shooting: 87, passing: 65, dribbling: 78,
    defending: 25, physical: 68, composure: 88, vision: 70,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_inzaghi.webp',
  },
  {
    id: 'vieri', shortName: 'Christian Vieri', fullName: 'Christian Vieri', position: 'ST',
    nation: 'Itália', club: 'Inter Milan', season: '1999/00', rarity: 'legendary', overall: 89,
    pace: 84, shooting: 90, passing: 65, dribbling: 80,
    defending: 30, physical: 89, composure: 87, vision: 68,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_vieri.webp',
  },
  {
    id: 'nedved', shortName: 'Pavel Nedvěd', fullName: 'Pavel Nedvěd', position: 'LM', secondaryPositions: ['CM'],
    nation: 'República Tcheca', club: 'Juventus', season: '2002/03', rarity: 'legendary', overall: 90,
    pace: 87, shooting: 82, passing: 84, dribbling: 88,
    defending: 60, physical: 84, composure: 88, vision: 85,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_nedved.webp',
  },
  {
    id: 'hierro', shortName: 'Fernando Hierro', fullName: 'Fernando Hierro', position: 'CB', secondaryPositions: ['CDM'],
    nation: 'Espanha', club: 'Real Madrid', season: '1999/00', rarity: 'legendary', overall: 88,
    pace: 68, shooting: 78, passing: 80, dribbling: 68,
    defending: 88, physical: 84, composure: 88, vision: 78,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_hierro.webp',
  },
  {
    id: 'patrick_vieira', shortName: 'Patrick Vieira', fullName: 'Patrick Vieira', position: 'CDM',
    nation: 'França', club: 'Arsenal', season: '2003/04', rarity: 'legendary', overall: 89,
    pace: 76, shooting: 68, passing: 82, dribbling: 78,
    defending: 87, physical: 90, composure: 88, vision: 80,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_patrick_vieira.webp',
  },
  {
    id: 'romario', shortName: 'Romário', fullName: 'Romário de Souza Faria', position: 'ST',
    nation: 'Brasil', club: 'Barcelona', season: '1993/94', rarity: 'immortal', overall: 93,
    pace: 88, shooting: 93, passing: 75, dribbling: 92,
    defending: 25, physical: 72, composure: 95, vision: 82,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_romario.webp',
  },
  {
    id: 'kluivert', shortName: 'Patrick Kluivert', fullName: 'Patrick Kluivert', position: 'ST',
    nation: 'Holanda', club: 'Barcelona', season: '1998/99', rarity: 'legendary', overall: 88,
    pace: 85, shooting: 87, passing: 75, dribbling: 85,
    defending: 30, physical: 80, composure: 86, vision: 76,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_kluivert.webp',
  },
  {
    id: 'ian_wright', shortName: 'Ian Wright', fullName: 'Ian Wright', position: 'ST',
    nation: 'Inglaterra', club: 'Arsenal', season: '1993/94', rarity: 'gold', overall: 86,
    pace: 88, shooting: 86, passing: 68, dribbling: 82,
    defending: 25, physical: 75, composure: 84, vision: 68,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_ian_wright.webp',
  },
  {
    id: 'sol_campbell', shortName: 'Sol Campbell', fullName: 'Sol Campbell', position: 'CB',
    nation: 'Inglaterra', club: 'Arsenal', season: '2003/04', rarity: 'gold', overall: 87,
    pace: 78, shooting: 40, passing: 68, dribbling: 60,
    defending: 89, physical: 89, composure: 85, vision: 65,
    traits: [],
    photoUrl: '/players/euro-legends/futwiz_sol_campbell.webp',
  },
];
