import type { Player } from './gameData';

/**
 * Lendas europeias das principais ligas (anos 90 até hoje) ainda ausentes do
 * catálogo, pesquisadas no SortitoutSI. Cada retrato foi verificado
 * individualmente (nome, nacionalidade e data de nascimento reais batendo
 * com o perfil do site) antes da inclusão — em alguns casos o jogador
 * aparece como comissão técnica/embaixador no banco de dados mais recente,
 * mas mantém a foto de jogador original.
 */
export const SORTITOUTSI_EUROPEAN_LEGENDS: Player[] = [
  {
    id: 'baggio', shortName: 'Roberto Baggio', fullName: 'Roberto Baggio', position: 'CAM', secondaryPositions: ['ST'], 
    nation: 'Itália', club: 'Juventus', season: '1993/94', rarity: 'legendary', overall: 93,
    pace: 93, shooting: 84, passing: 99, dribbling: 94,
    defending: 61, physical: 80, composure: 94, vision: 94,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_51.webp',
  },
  {
    id: 'raul', shortName: 'Raúl', fullName: 'Raúl', position: 'ST', 
    nation: 'Espanha', club: 'Real Madrid', season: '2000/01', rarity: 'legendary', overall: 92,
    pace: 93, shooting: 98, passing: 76, dribbling: 94,
    defending: 42, physical: 89, composure: 97, vision: 81,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_11952.webp',
  },
  {
    id: 'weah', shortName: 'George Weah', fullName: 'George Weah', position: 'ST', 
    nation: 'Libéria', club: 'Milan', season: '1995/96', rarity: 'legendary', overall: 92,
    pace: 92, shooting: 99, passing: 83, dribbling: 94,
    defending: 46, physical: 86, composure: 87, vision: 86,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_46.webp',
  },
  {
    id: 'keane', shortName: 'Roy Keane', fullName: 'Roy Keane', position: 'CDM', secondaryPositions: ['CM'], 
    nation: 'Irlanda', club: 'Manchester United', season: '1998/99', rarity: 'legendary', overall: 90,
    pace: 86, shooting: 69, passing: 92, dribbling: 78,
    defending: 85, physical: 85, composure: 91, vision: 80,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2014410.webp',
  },
  {
    id: 'rummenigge', shortName: 'Rummenigge', fullName: 'Rummenigge', position: 'ST', 
    nation: 'Alemanha', club: 'Bayern Munich', season: '1980/81', rarity: 'legendary', overall: 93,
    pace: 96, shooting: 97, passing: 82, dribbling: 96,
    defending: 51, physical: 94, composure: 98, vision: 78,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_500187.webp',
  },
  {
    id: 'hugo_sanchez', shortName: 'Hugo Sánchez', fullName: 'Hugo Sánchez', position: 'ST', 
    nation: 'México', club: 'Real Madrid', season: '1989/90', rarity: 'legendary', overall: 90,
    pace: 97, shooting: 90, passing: 78, dribbling: 95,
    defending: 42, physical: 88, composure: 95, vision: 78,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_5660995.webp',
  },
  {
    id: 'deco', shortName: 'Deco', fullName: 'Deco', position: 'CAM', secondaryPositions: ['CM'], 
    nation: 'Portugal', club: 'Porto', season: '2003/04', rarity: 'legendary', overall: 89,
    pace: 85, shooting: 76, passing: 93, dribbling: 97,
    defending: 53, physical: 83, composure: 86, vision: 97,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_4102655.webp',
  },
  {
    id: 'forlan', shortName: 'Diego Forlán', fullName: 'Diego Forlán', position: 'ST', 
    nation: 'Uruguai', club: 'Atlético Madrid', season: '2009/10', rarity: 'legendary', overall: 88,
    pace: 93, shooting: 97, passing: 74, dribbling: 91,
    defending: 38, physical: 84, composure: 91, vision: 74,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_3100536.webp',
  },
  {
    id: 'yaya_toure', shortName: 'Yaya Touré', fullName: 'Yaya Touré', position: 'CDM', secondaryPositions: ['CM'], 
    nation: 'Costa do Marfim', club: 'Manchester City', season: '2013/14', rarity: 'legendary', overall: 89,
    pace: 78, shooting: 68, passing: 87, dribbling: 80,
    defending: 83, physical: 90, composure: 92, vision: 88,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_533344.webp',
  },
  {
    id: 'torres_liverpool', shortName: 'Fernando Torres', fullName: 'Fernando Torres', position: 'ST', 
    nation: 'Espanha', club: 'Liverpool', season: '2007/08', rarity: 'legendary', overall: 88,
    pace: 96, shooting: 97, passing: 71, dribbling: 85,
    defending: 40, physical: 83, composure: 87, vision: 78,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_821112.webp',
  },
  {
    id: 'inzaghi', shortName: 'Filippo Inzaghi', fullName: 'Filippo Inzaghi', position: 'ST', 
    nation: 'Itália', club: 'Milan', season: '2006/07', rarity: 'gold', overall: 87,
    pace: 86, shooting: 87, passing: 72, dribbling: 86,
    defending: 41, physical: 84, composure: 88, vision: 79,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_811.webp',
  },
  {
    id: 'vieri', shortName: 'Christian Vieri', fullName: 'Christian Vieri', position: 'ST', 
    nation: 'Itália', club: 'Inter Milan', season: '1999/00', rarity: 'legendary', overall: 88,
    pace: 88, shooting: 89, passing: 74, dribbling: 88,
    defending: 43, physical: 86, composure: 90, vision: 81,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_3801524.webp',
  },
  {
    id: 'nedved', shortName: 'Pavel Nedvěd', fullName: 'Pavel Nedvěd', position: 'CAM', secondaryPositions: ['CM'], 
    nation: 'República Tcheca', club: 'Juventus', season: '2002/03', rarity: 'legendary', overall: 91,
    pace: 84, shooting: 85, passing: 90, dribbling: 93,
    defending: 59, physical: 77, composure: 90, vision: 99,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_8440.webp',
  },
  {
    id: 'trezeguet', shortName: 'David Trezeguet', fullName: 'David Trezeguet', position: 'ST', 
    nation: 'França', club: 'Juventus', season: '2002/03', rarity: 'gold', overall: 87,
    pace: 89, shooting: 90, passing: 75, dribbling: 89,
    defending: 44, physical: 87, composure: 91, vision: 82,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_9893.webp',
  },
  {
    id: 'cambiasso', shortName: 'Esteban Cambiasso', fullName: 'Esteban Cambiasso', position: 'CDM', 
    nation: 'Argentina', club: 'Inter Milan', season: '2009/10', rarity: 'gold', overall: 86,
    pace: 73, shooting: 66, passing: 88, dribbling: 73,
    defending: 79, physical: 89, composure: 83, vision: 82,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_3100494.webp',
  },
  {
    id: 'hierro', shortName: 'Fernando Hierro', fullName: 'Fernando Hierro', position: 'CB', secondaryPositions: ['CDM'], 
    nation: 'Espanha', club: 'Real Madrid', season: '1999/00', rarity: 'legendary', overall: 88,
    pace: 83, shooting: 47, passing: 80, dribbling: 55,
    defending: 87, physical: 86, composure: 80, vision: 65,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_11949.webp',
  },
  {
    id: 'godin', shortName: 'Diego Godín', fullName: 'Diego Godín', position: 'CB', 
    nation: 'Uruguai', club: 'Atlético Madrid', season: '2013/14', rarity: 'gold', overall: 87,
    pace: 76, shooting: 37, passing: 78, dribbling: 61,
    defending: 90, physical: 86, composure: 77, vision: 70,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_8826848.webp',
  },
  {
    id: 'rakitic', shortName: 'Ivan Rakitić', fullName: 'Ivan Rakitić', position: 'CM', 
    nation: 'Croácia', club: 'Barcelona', season: '2014/15', rarity: 'gold', overall: 87,
    pace: 85, shooting: 70, passing: 92, dribbling: 79,
    defending: 70, physical: 85, composure: 83, vision: 88,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_5727652.webp',
  },
  {
    id: 'john_terry', shortName: 'John Terry', fullName: 'John Terry', position: 'CB', 
    nation: 'Inglaterra', club: 'Chelsea', season: '2004/05', rarity: 'legendary', overall: 89,
    pace: 84, shooting: 48, passing: 81, dribbling: 56,
    defending: 88, physical: 87, composure: 81, vision: 66,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_108625.webp',
  },
  {
    id: 'patrick_vieira', shortName: 'Patrick Vieira', fullName: 'Patrick Vieira', position: 'CDM', 
    nation: 'França', club: 'Arsenal', season: '2003/04', rarity: 'legendary', overall: 89,
    pace: 83, shooting: 66, passing: 89, dribbling: 75,
    defending: 82, physical: 82, composure: 88, vision: 88,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2007286.webp',
  },
  {
    id: 'kounde', shortName: 'Jules Koundé', fullName: 'Jules Koundé', position: 'CB', secondaryPositions: ['RB'], 
    nation: 'França', club: 'Barcelona', season: '2024/25', rarity: 'gold', overall: 85,
    pace: 78, shooting: 45, passing: 70, dribbling: 59,
    defending: 83, physical: 85, composure: 82, vision: 59,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_48036304.webp',
  },
  {
    id: 'thomas_muller', shortName: 'Thomas Müller', fullName: 'Thomas Müller', position: 'CAM', secondaryPositions: ['ST'], 
    nation: 'Alemanha', club: 'Bayern Munich', season: '2013/14', rarity: 'legendary', overall: 88,
    pace: 88, shooting: 77, passing: 92, dribbling: 94,
    defending: 48, physical: 76, composure: 88, vision: 97,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_35011448.webp',
  },
  {
    id: 'gotze', shortName: 'Mario Götze', fullName: 'Mario Götze', position: 'CAM', 
    nation: 'Alemanha', club: 'Borussia Dortmund', season: '2012/13', rarity: 'gold', overall: 86,
    pace: 80, shooting: 75, passing: 85, dribbling: 93,
    defending: 53, physical: 76, composure: 83, vision: 87,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_35017438.webp',
  },
  {
    id: 'romario', shortName: 'Romário', fullName: 'Romário', position: 'ST', 
    nation: 'Brasil', club: 'Barcelona', season: '1993/94', rarity: 'legendary', overall: 93,
    pace: 93, shooting: 97, passing: 85, dribbling: 91,
    defending: 49, physical: 95, composure: 91, vision: 85,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_14643.webp',
  },
  {
    id: 'kluivert', shortName: 'Patrick Kluivert', fullName: 'Patrick Kluivert', position: 'ST', 
    nation: 'Holanda', club: 'Ajax', season: '1994/95', rarity: 'legendary', overall: 89,
    pace: 90, shooting: 88, passing: 81, dribbling: 92,
    defending: 44, physical: 84, composure: 85, vision: 84,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_4200584.webp',
  },
  {
    id: 'sheringham', shortName: 'Teddy Sheringham', fullName: 'Teddy Sheringham', position: 'ST', secondaryPositions: ['CAM'], 
    nation: 'Inglaterra', club: 'Manchester United', season: '1998/99', rarity: 'gold', overall: 86,
    pace: 92, shooting: 90, passing: 72, dribbling: 83,
    defending: 46, physical: 86, composure: 87, vision: 75,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2005486.webp',
  },
  {
    id: 'ian_wright', shortName: 'Ian Wright', fullName: 'Ian Wright', position: 'ST', 
    nation: 'Inglaterra', club: 'Arsenal', season: '1993/94', rarity: 'gold', overall: 87,
    pace: 96, shooting: 86, passing: 71, dribbling: 85,
    defending: 40, physical: 83, composure: 87, vision: 78,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2006032.webp',
  },
  {
    id: 'tony_adams', shortName: 'Tony Adams', fullName: 'Tony Adams', position: 'CB', 
    nation: 'Inglaterra', club: 'Arsenal', season: '1997/98', rarity: 'gold', overall: 87,
    pace: 82, shooting: 46, passing: 79, dribbling: 54,
    defending: 86, physical: 85, composure: 79, vision: 64,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2003258.webp',
  },
  {
    id: 'asprilla', shortName: 'Faustino Asprilla', fullName: 'Faustino Asprilla', position: 'ST', secondaryPositions: ['RW'], 
    nation: 'Colômbia', club: 'Newcastle', season: '1995/96', rarity: 'gold', overall: 84,
    pace: 86, shooting: 90, passing: 67, dribbling: 84,
    defending: 42, physical: 77, composure: 84, vision: 78,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2001891.webp',
  },
  {
    id: 'sol_campbell', shortName: 'Sol Campbell', fullName: 'Sol Campbell', position: 'CB', 
    nation: 'Inglaterra', club: 'Arsenal', season: '2003/04', rarity: 'gold', overall: 87,
    pace: 80, shooting: 47, passing: 72, dribbling: 61,
    defending: 85, physical: 87, composure: 84, vision: 61,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2003678.webp',
  },
  {
    id: 'jesus_navas', shortName: 'Jesús Navas', fullName: 'Jesús Navas', position: 'RW', secondaryPositions: ['RB'], 
    nation: 'Espanha', club: 'Sevilla', season: '2006/07', rarity: 'gold', overall: 84,
    pace: 88, shooting: 74, passing: 85, dribbling: 93,
    defending: 45, physical: 75, composure: 78, vision: 77,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_7456721.webp',
  },
  {
    id: 'kanoute', shortName: 'Frédéric Kanouté', fullName: 'Frédéric Kanouté', position: 'ST', 
    nation: 'Mali', club: 'Sevilla', season: '2006/07', rarity: 'gold', overall: 85,
    pace: 87, shooting: 85, passing: 78, dribbling: 89,
    defending: 41, physical: 81, composure: 82, vision: 70,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_400823.webp',
  },
  {
    id: 'canizares', shortName: 'Santiago Cañizares', fullName: 'Santiago Cañizares', position: 'GK', 
    nation: 'Espanha', club: 'Valencia', season: '2001/02', rarity: 'gold', overall: 84,
    pace: 71, shooting: 3, passing: 59, dribbling: 50,
    defending: 89, physical: 73, composure: 81, vision: 69,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_11958.webp',
  },
  {
    id: 'baraja', shortName: 'Rubén Baraja', fullName: 'Rubén Baraja', position: 'CM', 
    nation: 'Espanha', club: 'Valencia', season: '2001/02', rarity: 'gold', overall: 84,
    pace: 78, shooting: 74, passing: 85, dribbling: 83,
    defending: 63, physical: 78, composure: 87, vision: 81,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_14674.webp',
  },
  {
    id: 'aimar', shortName: 'Pablo Aimar', fullName: 'Pablo Aimar', position: 'CAM', 
    nation: 'Argentina', club: 'Valencia', season: '2003/04', rarity: 'gold', overall: 86,
    pace: 80, shooting: 75, passing: 85, dribbling: 93,
    defending: 53, physical: 76, composure: 83, vision: 87,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2000111.webp',
  },
  {
    id: 'nuno_gomes', shortName: 'Nuno Gomes', fullName: 'Nuno Gomes', position: 'ST', 
    nation: 'Portugal', club: 'Benfica', season: '2004/05', rarity: 'gold', overall: 85,
    pace: 84, shooting: 85, passing: 70, dribbling: 84,
    defending: 39, physical: 82, composure: 86, vision: 77,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_1601.webp',
  },
  {
    id: 'vitor_baia', shortName: 'Vítor Baía', fullName: 'Vítor Baía', position: 'GK', 
    nation: 'Portugal', club: 'Porto', season: '2003/04', rarity: 'gold', overall: 87,
    pace: 69, shooting: 7, passing: 64, dribbling: 53,
    defending: 90, physical: 83, composure: 89, vision: 75,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_1106.webp',
  },
  {
    id: 'juninho_pernambucano', shortName: 'Juninho Pernambucano', fullName: 'Juninho Pernambucano', position: 'CM', 
    nation: 'Brasil', club: 'Lyon', season: '2005/06', rarity: 'gold', overall: 87,
    pace: 82, shooting: 75, passing: 94, dribbling: 89,
    defending: 66, physical: 78, composure: 84, vision: 86,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_3300008.webp',
  },
  {
    id: 'radebe', shortName: 'Lucas Radebe', fullName: 'Lucas Radebe', position: 'CB', 
    nation: 'África do Sul', club: 'Leeds', season: '1999/00', rarity: 'gold', overall: 82,
    pace: 77, shooting: 33, passing: 69, dribbling: 58,
    defending: 82, physical: 84, composure: 81, vision: 58,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2016464.webp',
  },
  {
    id: 'woodgate', shortName: 'Jonathan Woodgate', fullName: 'Jonathan Woodgate', position: 'CB', 
    nation: 'Inglaterra', club: 'Leeds', season: '1999/00', rarity: 'gold', overall: 81,
    pace: 78, shooting: 34, passing: 70, dribbling: 48,
    defending: 83, physical: 85, composure: 71, vision: 59,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_106708.webp',
  },
  {
    id: 'les_ferdinand', shortName: 'Les Ferdinand', fullName: 'Les Ferdinand', position: 'ST', 
    nation: 'Inglaterra', club: 'Newcastle', season: '1995/96', rarity: 'gold', overall: 84,
    pace: 88, shooting: 91, passing: 67, dribbling: 83,
    defending: 40, physical: 85, composure: 80, vision: 73,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2004088.webp',
  },
  {
    id: 'beardsley', shortName: 'Peter Beardsley', fullName: 'Peter Beardsley', position: 'CAM', secondaryPositions: ['ST'], 
    nation: 'Inglaterra', club: 'Newcastle', season: '1994/95', rarity: 'gold', overall: 83,
    pace: 78, shooting: 76, passing: 89, dribbling: 89,
    defending: 52, physical: 78, composure: 77, vision: 84,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_2003432.webp',
  },
  {
    id: 'gerd_muller', shortName: 'Gerd Müller', fullName: 'Gerd Müller', position: 'ST', 
    nation: 'Alemanha', club: 'Bayern Munich', season: '1972/73', rarity: 'immortal', overall: 95,
    pace: 94, shooting: 99, passing: 85, dribbling: 96,
    defending: 48, physical: 88, composure: 99, vision: 88,
    traits: [],
    photoUrl: '/players/euro-legends/sortitoutsi_3600230.webp',
  },
];
