import type { Player } from '../gameData';

/**
 * Jogadores famosos (FIFA 15 → FC 27) que ainda faltavam no catálogo, triados
 * nos rankings por posição do fifaindex.com. Atributos e clube vêm da edição em
 * que cada um teve a maior nota; a foto é o rosto oficial dessa mesma edição
 * (CDN do sofifa, pelo ID EA), convertida sem achatar a transparência.
 */
export const FIFAINDEX_FAMOUS_ADDITIONS: Player[] = [
  { id: 'higuain_juventus', shortName: 'Higuaín', fullName: 'Gonzalo Higuaín', position: 'ST', nation: 'Argentina', club: 'Juventus', season: '2017/18', rarity: 'legendary', overall: 90,
    pace: 79, shooting: 85, passing: 69, dribbling: 81, defending: 32, physical: 72, composure: 86, vision: 74, traits: [], photoUrl: '/players/fifaindex-famous/167664.webp' },
  { id: 'ozil_arsenal', shortName: 'Özil', fullName: 'Mesut Özil', position: 'CAM', nation: 'Alemanha', club: 'Arsenal', season: '2016/17', rarity: 'legendary', overall: 89,
    pace: 72, shooting: 75, passing: 88, dribbling: 82, defending: 27, physical: 56, composure: 73, vision: 93, traits: [], photoUrl: '/players/fifaindex-famous/176635.webp' },
  { id: 'boateng_bayern_munich', shortName: 'J. Boateng', fullName: 'Jérôme Boateng', position: 'CB', nation: 'Alemanha', club: 'Bayern Munich', season: '2016/17', rarity: 'legendary', overall: 89,
    pace: 77, shooting: 53, passing: 77, dribbling: 70, defending: 89, physical: 81, composure: 86, vision: 76, traits: [], photoUrl: '/players/fifaindex-famous/183907.webp' },
  { id: 'pacho_paris_saint_germain', shortName: 'Pacho', fullName: 'Willian Pacho', position: 'CB', nation: 'Equador', club: 'Paris Saint-Germain', season: '2026/27', rarity: 'legendary', overall: 89,
    pace: 79, shooting: 34, passing: 68, dribbling: 71, defending: 88, physical: 86, composure: 84, vision: 58, traits: [], photoUrl: '/players/fifaindex-famous/256196.webp' },
  { id: 'riquelme_boca_juniors', shortName: 'Riquelme', fullName: 'Juan Román Riquelme', position: 'CAM', nation: 'Argentina', club: 'Boca Juniors', season: '2000/01', rarity: 'legendary', overall: 88,
    pace: 70, shooting: 83, passing: 91, dribbling: 87, defending: 36, physical: 63, composure: 92, vision: 92, traits: [], photoUrl: '/players/fifaindex-famous/23174.webp' },
  { id: 'handanovic_inter_milan', shortName: 'Handanovič', fullName: 'Samir Handanovič', position: 'GK', nation: 'Eslovênia', club: 'Inter Milan', season: '2018/19', rarity: 'legendary', overall: 88,
    pace: 53, shooting: 16, passing: 37, dribbling: 44, defending: 92, physical: 78, composure: 69, vision: 41, traits: [], photoUrl: '/players/fifaindex-famous/162835.webp' },
  { id: 'thiago_bayern_munich', shortName: 'Thiago', fullName: 'Thiago Alcântara', position: 'CM', nation: 'Espanha', club: 'Bayern Munich', season: '2017/18', rarity: 'legendary', overall: 88,
    pace: 73, shooting: 79, passing: 89, dribbling: 88, defending: 63, physical: 67, composure: 83, vision: 86, traits: [], photoUrl: '/players/fifaindex-famous/189509.webp' },
  { id: 'pogba_manchester_united', shortName: 'Pogba', fullName: 'Paul Pogba', position: 'CM', nation: 'França', club: 'Manchester United', season: '2018/19', rarity: 'legendary', overall: 88,
    pace: 75, shooting: 83, passing: 88, dribbling: 81, defending: 67, physical: 84, composure: 87, vision: 88, traits: [], photoUrl: '/players/fifaindex-famous/195864.webp' },
  { id: 'koulibaly_napoli', shortName: 'Koulibaly', fullName: 'Kalidou Koulibaly', position: 'CB', nation: 'Senegal', club: 'Napoli', season: '2019/20', rarity: 'legendary', overall: 88,
    pace: 71, shooting: 29, passing: 62, dribbling: 67, defending: 87, physical: 84, composure: 82, vision: 52, traits: [], photoUrl: '/players/fifaindex-famous/201024.webp' },
  { id: 'raya_arsenal', shortName: 'Raya', fullName: 'David Raya', position: 'GK', nation: 'Espanha', club: 'Arsenal', season: '2026/27', rarity: 'legendary', overall: 88,
    pace: 58, shooting: 27, passing: 66, dribbling: 56, defending: 92, physical: 78, composure: 70, vision: 69, traits: [], photoUrl: '/players/fifaindex-famous/220901.webp' },
  { id: 'vertonghen_tottenham', shortName: 'Vertonghen', fullName: 'Jan Vertonghen', position: 'CB', nation: 'Bélgica', club: 'Tottenham', season: '2018/19', rarity: 'gold', overall: 87,
    pace: 63, shooting: 63, passing: 73, dribbling: 73, defending: 87, physical: 81, composure: 83, vision: 68, traits: [], photoUrl: '/players/fifaindex-famous/172871.webp' },
  { id: 'alderweireld_tottenham', shortName: 'Alderweireld', fullName: 'Toby Alderweireld', position: 'CB', nation: 'Bélgica', club: 'Tottenham', season: '2018/19', rarity: 'gold', overall: 87,
    pace: 64, shooting: 57, passing: 77, dribbling: 70, defending: 87, physical: 81, composure: 84, vision: 67, traits: [], photoUrl: '/players/fifaindex-famous/184087.webp' },
  { id: 'bonucci_juventus', shortName: 'Bonucci', fullName: 'Leonardo Bonucci', position: 'CB', nation: 'Itália', club: 'Juventus', season: '2016/17', rarity: 'gold', overall: 87,
    pace: 70, shooting: 57, passing: 77, dribbling: 71, defending: 87, physical: 81, composure: 82, vision: 74, traits: [], photoUrl: '/players/fifaindex-famous/184344.webp' },
  { id: 'icardi_inter_milan', shortName: 'Icardi', fullName: 'Mauro Icardi', position: 'ST', nation: 'Argentina', club: 'Inter Milan', season: '2018/19', rarity: 'gold', overall: 87,
    pace: 77, shooting: 84, passing: 63, dribbling: 81, defending: 40, physical: 74, composure: 85, vision: 64, traits: [], photoUrl: '/players/fifaindex-famous/201399.webp' },
  { id: 'umtiti_barcelona', shortName: 'Umtiti', fullName: 'Samuel Umtiti', position: 'CB', nation: 'França', club: 'Barcelona', season: '2018/19', rarity: 'gold', overall: 87,
    pace: 72, shooting: 66, passing: 70, dribbling: 74, defending: 86, physical: 82, composure: 82, vision: 58, traits: [], photoUrl: '/players/fifaindex-famous/205600.webp' },
  { id: 'laporte_manchester_city', shortName: 'Laporte', fullName: 'Aymeric Laporte', position: 'CB', nation: 'França', club: 'Manchester City', season: '2019/20', rarity: 'gold', overall: 87,
    pace: 63, shooting: 50, passing: 75, dribbling: 72, defending: 88, physical: 79, composure: 85, vision: 65, traits: [], photoUrl: '/players/fifaindex-famous/212218.webp' },
  { id: 'barzagli_juventus', shortName: 'Barzagli', fullName: 'Andrea Barzagli', position: 'CB', nation: 'Itália', club: 'Juventus', season: '2016/17', rarity: 'gold', overall: 86,
    pace: 74, shooting: 41, passing: 62, dribbling: 69, defending: 88, physical: 79, composure: 82, vision: 58, traits: [], photoUrl: '/players/fifaindex-famous/137186.webp' },
  { id: 'papu_gomez_atalanta', shortName: 'Papu Gómez', fullName: 'Alejandro Gómez', position: 'CAM', nation: 'Argentina', club: 'Atalanta', season: '2020/21', rarity: 'gold', overall: 86,
    pace: 88, shooting: 77, passing: 84, dribbling: 88, defending: 38, physical: 61, composure: 85, vision: 87, traits: [], photoUrl: '/players/fifaindex-famous/143076.webp' },
  { id: 'nainggolan_roma', shortName: 'Nainggolan', fullName: 'Radja Nainggolan', position: 'CM', nation: 'Bélgica', club: 'Roma', season: '2016/17', rarity: 'gold', overall: 86,
    pace: 79, shooting: 79, passing: 80, dribbling: 84, defending: 79, physical: 84, composure: 85, vision: 76, traits: [], photoUrl: '/players/fifaindex-famous/178518.webp' },
  { id: 'trapp_eintracht_frankfurt', shortName: 'Trapp', fullName: 'Kevin Trapp', position: 'GK', nation: 'Alemanha', club: 'Eintracht Frankfurt', season: '2022/23', rarity: 'gold', overall: 86,
    pace: 46, shooting: 21, passing: 27, dribbling: 44, defending: 90, physical: 76, composure: 64, vision: 46, traits: [], photoUrl: '/players/fifaindex-famous/188943.webp' },
  { id: 'leno_bayer_leverkusen', shortName: 'Leno', fullName: 'Bernd Leno', position: 'GK', nation: 'Alemanha', club: 'Bayer Leverkusen', season: '2016/17', rarity: 'gold', overall: 86,
    pace: 49, shooting: 14, passing: 41, dribbling: 46, defending: 90, physical: 76, composure: 62, vision: 53, traits: [], photoUrl: '/players/fifaindex-famous/192563.webp' },
  { id: 'gerard_moreno_villarreal', shortName: 'Gerard Moreno', fullName: 'Gerard Moreno Balagueró', position: 'ST', nation: 'Espanha', club: 'Villarreal', season: '2021/22', rarity: 'gold', overall: 86,
    pace: 79, shooting: 85, passing: 78, dribbling: 81, defending: 50, physical: 73, composure: 78, vision: 78, traits: [], photoUrl: '/players/fifaindex-famous/208093.webp' },
  { id: 'ziyech_ajax', shortName: 'Ziyech', fullName: 'Hakim Ziyech', position: 'CAM', nation: 'Marrocos', club: 'Ajax', season: '2019/20', rarity: 'gold', overall: 86,
    pace: 80, shooting: 76, passing: 88, dribbling: 83, defending: 49, physical: 63, composure: 79, vision: 89, traits: [], photoUrl: '/players/fifaindex-famous/208670.webp' },
  { id: 'werner_rb_leipzig', shortName: 'Werner', fullName: 'Timo Werner', position: 'ST', nation: 'Alemanha', club: 'RB Leipzig', season: '2019/20', rarity: 'gold', overall: 86,
    pace: 92, shooting: 84, passing: 65, dribbling: 83, defending: 39, physical: 72, composure: 80, vision: 64, traits: [], photoUrl: '/players/fifaindex-famous/212188.webp' },
  { id: 'lenglet_barcelona', shortName: 'Lenglet', fullName: 'Clément Lenglet', position: 'CB', nation: 'França', club: 'Barcelona', season: '2019/20', rarity: 'gold', overall: 86,
    pace: 75, shooting: 47, passing: 72, dribbling: 70, defending: 85, physical: 81, composure: 82, vision: 66, traits: [], photoUrl: '/players/fifaindex-famous/220440.webp' },
  { id: 'sane_bayern_munich', shortName: 'L. Sané', fullName: 'Leroy Sané', position: 'RM', nation: 'Alemanha', club: 'Bayern Munich', season: '2023/24', rarity: 'gold', overall: 86,
    pace: 90, shooting: 80, passing: 78, dribbling: 85, defending: 40, physical: 69, composure: 83, vision: 81, traits: [], photoUrl: '/players/fifaindex-famous/222492.webp' },
  { id: 'skriniar_inter_milan', shortName: 'Škriniar', fullName: 'Milan Škriniar', position: 'CB', nation: 'Eslováquia', club: 'Inter Milan', season: '2021/22', rarity: 'gold', overall: 86,
    pace: 80, shooting: 41, passing: 59, dribbling: 71, defending: 86, physical: 84, composure: 87, vision: 46, traits: [], photoUrl: '/players/fifaindex-famous/232363.webp' },
  { id: 'nkunku_rb_leipzig', shortName: 'Nkunku', fullName: 'Christopher Nkunku', position: 'ST', nation: 'França', club: 'RB Leipzig', season: '2022/23', rarity: 'gold', overall: 86,
    pace: 83, shooting: 78, passing: 83, dribbling: 87, defending: 61, physical: 65, composure: 81, vision: 84, traits: [], photoUrl: '/players/fifaindex-famous/232411.webp' },
  { id: 'carnesecchi_atalanta', shortName: 'Carnesecchi', fullName: 'Marco Carnesecchi', position: 'GK', nation: 'Itália', club: 'Atalanta', season: '2026/27', rarity: 'gold', overall: 86,
    pace: 31, shooting: 18, passing: 46, dribbling: 36, defending: 90, physical: 76, composure: 40, vision: 58, traits: [], photoUrl: '/players/fifaindex-famous/252154.webp' },
  { id: 'joan_garcia_barcelona', shortName: 'Joan García', fullName: 'Joan García', position: 'GK', nation: 'Espanha', club: 'Barcelona', season: '2026/27', rarity: 'gold', overall: 86,
    pace: 46, shooting: 18, passing: 54, dribbling: 47, defending: 90, physical: 76, composure: 59, vision: 63, traits: [], photoUrl: '/players/fifaindex-famous/259532.webp' },
  { id: 'payet_marseille', shortName: 'Payet', fullName: 'Dimitri Payet', position: 'LM', nation: 'França', club: 'Marseille', season: '2016/17', rarity: 'gold', overall: 85,
    pace: 77, shooting: 79, passing: 85, dribbling: 84, defending: 40, physical: 64, composure: 86, vision: 87, traits: [], photoUrl: '/players/fifaindex-famous/177388.webp' },
  { id: 'witsel_borussia_dortmund', shortName: 'Witsel', fullName: 'Axel Witsel', position: 'CDM', nation: 'Bélgica', club: 'Borussia Dortmund', season: '2018/19', rarity: 'gold', overall: 85,
    pace: 70, shooting: 77, passing: 84, dribbling: 81, defending: 82, physical: 81, composure: 92, vision: 80, traits: [], photoUrl: '/players/fifaindex-famous/177413.webp' },
  { id: 'wijnaldum_liverpool', shortName: 'Wijnaldum', fullName: 'Georginio Wijnaldum', position: 'CM', nation: 'Holanda', club: 'Liverpool', season: '2019/20', rarity: 'gold', overall: 85,
    pace: 77, shooting: 75, passing: 82, dribbling: 86, defending: 76, physical: 81, composure: 86, vision: 79, traits: [], photoUrl: '/players/fifaindex-famous/181291.webp' },
  { id: 'gulacsi_rb_leipzig', shortName: 'Gulácsi', fullName: 'Péter Gulácsi', position: 'GK', nation: 'Hungria', club: 'RB Leipzig', season: '2022/23', rarity: 'gold', overall: 85,
    pace: 43, shooting: 21, passing: 36, dribbling: 42, defending: 89, physical: 75, composure: 45, vision: 44, traits: [], photoUrl: '/players/fifaindex-famous/185122.webp' },
  { id: 'trippier_newcastle', shortName: 'Trippier', fullName: 'Kieran Trippier', position: 'RB', nation: 'Inglaterra', club: 'Newcastle', season: '2023/24', rarity: 'gold', overall: 85,
    pace: 68, shooting: 68, passing: 85, dribbling: 79, defending: 81, physical: 76, composure: 83, vision: 85, traits: [], photoUrl: '/players/fifaindex-famous/186345.webp' },
  { id: 'aspas_celta_vigo', shortName: 'Aspas', fullName: 'Iago Aspas Juncal', position: 'ST', nation: 'Espanha', club: 'Celta Vigo', season: '2022/23', rarity: 'gold', overall: 85,
    pace: 81, shooting: 84, passing: 77, dribbling: 84, defending: 39, physical: 65, composure: 85, vision: 81, traits: [], photoUrl: '/players/fifaindex-famous/192629.webp' },
  { id: 'manolas_roma', shortName: 'Manolas', fullName: 'Kostas Manolas', position: 'CB', nation: 'Grécia', club: 'Roma', season: '2017/18', rarity: 'gold', overall: 85,
    pace: 83, shooting: 22, passing: 47, dribbling: 69, defending: 86, physical: 84, composure: 79, vision: 22, traits: [], photoUrl: '/players/fifaindex-famous/192774.webp' },
  { id: 'casteels_wolfsburg', shortName: 'Casteels', fullName: 'Koen Casteels', position: 'GK', nation: 'Bélgica', club: 'Wolfsburg', season: '2021/22', rarity: 'gold', overall: 85,
    pace: 45, shooting: 23, passing: 38, dribbling: 42, defending: 89, physical: 75, composure: 40, vision: 42, traits: [], photoUrl: '/players/fifaindex-famous/192984.webp' },
  { id: 'pizzi_benfica', shortName: 'Pizzi', fullName: 'Luis Miguel Afonso Fernandes', position: 'RM', nation: 'Portugal', club: 'Benfica', season: '2019/20', rarity: 'gold', overall: 85,
    pace: 77, shooting: 79, passing: 85, dribbling: 82, defending: 61, physical: 71, composure: 85, vision: 86, traits: [], photoUrl: '/players/fifaindex-famous/197965.webp' },
  { id: 'de_vrij_inter_milan', shortName: 'De Vrij', fullName: 'Stefan de Vrij', position: 'CB', nation: 'Holanda', club: 'Inter Milan', season: '2019/20', rarity: 'gold', overall: 85,
    pace: 65, shooting: 42, passing: 69, dribbling: 70, defending: 86, physical: 75, composure: 82, vision: 64, traits: [], photoUrl: '/players/fifaindex-famous/198176.webp' },
  { id: 'lopes_lyon', shortName: 'A. Lopes', fullName: 'Anthony Lopes', position: 'GK', nation: 'Portugal', club: 'Lyon', season: '2018/19', rarity: 'gold', overall: 85,
    pace: 63, shooting: 16, passing: 37, dribbling: 52, defending: 89, physical: 75, composure: 65, vision: 48, traits: [], photoUrl: '/players/fifaindex-famous/199482.webp' },
  { id: 'bono_sevilla', shortName: 'Bono', fullName: 'Yassine Bounou', position: 'GK', nation: 'Marrocos', club: 'Sevilla', season: '2022/23', rarity: 'gold', overall: 85,
    pace: 37, shooting: 23, passing: 48, dribbling: 41, defending: 89, physical: 75, composure: 57, vision: 62, traits: [], photoUrl: '/players/fifaindex-famous/209981.webp' },
  { id: 'berardi_sassuolo', shortName: 'Berardi', fullName: 'Domenico Berardi', position: 'RW', nation: 'Itália', club: 'Sassuolo', season: '2023/24', rarity: 'gold', overall: 85,
    pace: 82, shooting: 81, passing: 82, dribbling: 86, defending: 38, physical: 76, composure: 78, vision: 83, traits: [], photoUrl: '/players/fifaindex-famous/210935.webp' },
  { id: 'dele_alli_tottenham', shortName: 'Dele Alli', fullName: 'Dele Alli', position: 'CAM', nation: 'Inglaterra', club: 'Tottenham', season: '2018/19', rarity: 'gold', overall: 85,
    pace: 74, shooting: 80, passing: 83, dribbling: 80, defending: 72, physical: 78, composure: 87, vision: 85, traits: [], photoUrl: '/players/fifaindex-famous/211117.webp' },
  { id: 'sule_bayern_munich', shortName: 'Süle', fullName: 'Niklas Süle', position: 'CB', nation: 'Alemanha', club: 'Bayern Munich', season: '2019/20', rarity: 'gold', overall: 85,
    pace: 68, shooting: 42, passing: 62, dribbling: 55, defending: 86, physical: 69, composure: 75, vision: 40, traits: [], photoUrl: '/players/fifaindex-famous/212190.webp' },
  { id: 'gimenez_atletico_madrid', shortName: 'Giménez', fullName: 'José María Giménez', position: 'CB', nation: 'Uruguai', club: 'Atlético Madrid', season: '2019/20', rarity: 'gold', overall: 85,
    pace: 68, shooting: 42, passing: 52, dribbling: 60, defending: 85, physical: 83, composure: 75, vision: 27, traits: [], photoUrl: '/players/fifaindex-famous/216460.webp' },
  { id: 'fekir_real_betis', shortName: 'Fekir', fullName: 'Nabil Fekir', position: 'CAM', nation: 'França', club: 'Real Betis', season: '2021/22', rarity: 'gold', overall: 85,
    pace: 83, shooting: 81, passing: 82, dribbling: 87, defending: 38, physical: 76, composure: 89, vision: 84, traits: [], photoUrl: '/players/fifaindex-famous/216594.webp' },
  { id: 'ruben_neves_wolves', shortName: 'Rúben Neves', fullName: 'Rúben Neves', position: 'CDM', nation: 'Portugal', club: 'Wolves', season: '2022/23', rarity: 'gold', overall: 83,
    pace: 60, shooting: 76, passing: 87, dribbling: 78, defending: 73, physical: 74, composure: 88, vision: 87, traits: [], photoUrl: '/players/fifaindex-famous/224293.webp' },
  { id: 'diogo_jota_liverpool', shortName: 'Diogo Jota', fullName: 'Diogo Jota', position: 'ST', nation: 'Portugal', club: 'Liverpool', season: '2023/24', rarity: 'gold', overall: 85,
    pace: 82, shooting: 81, passing: 75, dribbling: 85, defending: 59, physical: 83, composure: 83, vision: 78, traits: [], photoUrl: '/players/fifaindex-famous/224458.webp' },
  { id: 'llorente_atletico_madrid', shortName: 'Llorente', fullName: 'Marcos Llorente Moreno', position: 'CM', nation: 'Espanha', club: 'Atlético Madrid', season: '2021/22', rarity: 'gold', overall: 85,
    pace: 87, shooting: 76, passing: 84, dribbling: 81, defending: 76, physical: 80, composure: 83, vision: 85, traits: [], photoUrl: '/players/fifaindex-famous/226161.webp' },
  { id: 'unai_simon_athletic_bilbao', shortName: 'Unai Simón', fullName: 'Unai Simón', position: 'GK', nation: 'Espanha', club: 'Athletic Bilbao', season: '2026/27', rarity: 'gold', overall: 85,
    pace: 49, shooting: 23, passing: 40, dribbling: 39, defending: 89, physical: 75, composure: 40, vision: 48, traits: [], photoUrl: '/players/fifaindex-famous/230869.webp' },
  { id: 'svilar_roma', shortName: 'Svilar', fullName: 'Mile Svilar', position: 'GK', nation: 'Sérvia', club: 'Roma', season: '2026/27', rarity: 'gold', overall: 85,
    pace: 57, shooting: 26, passing: 52, dribbling: 51, defending: 89, physical: 75, composure: 48, vision: 58, traits: [], photoUrl: '/players/fifaindex-famous/230872.webp' },
  { id: 'de_ligt_juventus', shortName: 'De Ligt', fullName: 'Matthijs de Ligt', position: 'CB', nation: 'Holanda', club: 'Juventus', season: '2021/22', rarity: 'gold', overall: 85,
    pace: 75, shooting: 55, passing: 62, dribbling: 71, defending: 84, physical: 86, composure: 82, vision: 45, traits: [], photoUrl: '/players/fifaindex-famous/235243.webp' },
  { id: 'guehi_manchester_city', shortName: 'Guéhi', fullName: 'Marc Guéhi', position: 'CB', nation: 'Inglaterra', club: 'Manchester City', season: '2026/27', rarity: 'gold', overall: 85,
    pace: 69, shooting: 47, passing: 75, dribbling: 73, defending: 85, physical: 83, composure: 80, vision: 67, traits: [], photoUrl: '/players/fifaindex-famous/241159.webp' },
  { id: 'semenyo_manchester_city', shortName: 'Semenyo', fullName: 'Antoine Semenyo', position: 'RW', nation: 'Gana', club: 'Manchester City', season: '2026/27', rarity: 'gold', overall: 85,
    pace: 81, shooting: 83, passing: 78, dribbling: 83, defending: 47, physical: 81, composure: 85, vision: 83, traits: [], photoUrl: '/players/fifaindex-famous/241236.webp' },
  { id: 'mbeumo_manchester_united', shortName: 'Mbeumo', fullName: 'Bryan Mbeumo', position: 'RW', nation: 'Camarões', club: 'Manchester United', season: '2025/26', rarity: 'gold', overall: 85,
    pace: 90, shooting: 84, passing: 76, dribbling: 85, defending: 49, physical: 78, composure: 83, vision: 80, traits: [], photoUrl: '/players/fifaindex-famous/243014.webp' },
  { id: 'eric_garcia_barcelona', shortName: 'Eric García', fullName: 'Eric García', position: 'CB', nation: 'Espanha', club: 'Barcelona', season: '2026/27', rarity: 'gold', overall: 85,
    pace: 79, shooting: 57, passing: 82, dribbling: 77, defending: 84, physical: 83, composure: 84, vision: 79, traits: [], photoUrl: '/players/fifaindex-famous/245037.webp' },
  { id: 'zubimendi_arsenal', shortName: 'Zubimendi', fullName: 'Martín Zubimendi', position: 'CDM', nation: 'Espanha', club: 'Arsenal', season: '2025/26', rarity: 'gold', overall: 85,
    pace: 66, shooting: 69, passing: 85, dribbling: 81, defending: 80, physical: 78, composure: 85, vision: 84, traits: [], photoUrl: '/players/fifaindex-famous/248148.webp' },
  { id: 'fermin_barcelona', shortName: 'Fermín', fullName: 'Fermín López', position: 'CAM', nation: 'Espanha', club: 'Barcelona', season: '2026/27', rarity: 'gold', overall: 85,
    pace: 80, shooting: 80, passing: 83, dribbling: 83, defending: 66, physical: 77, composure: 83, vision: 84, traits: [], photoUrl: '/players/fifaindex-famous/277179.webp' },
  { id: 'arda_turan_atletico_madrid', shortName: 'Arda Turan', fullName: 'Arda Turan', position: 'RM', nation: 'Turquia', club: 'Atlético Madrid', season: '2014/15', rarity: 'gold', overall: 84,
    pace: 76, shooting: 76, passing: 83, dribbling: 86, defending: 64, physical: 76, composure: 84, vision: 86, traits: [], photoUrl: '/players/fifaindex-famous/143745.webp' },
  { id: 'joe_hart_manchester_city', shortName: 'Joe Hart', fullName: 'Joe Hart', position: 'GK', nation: 'Inglaterra', club: 'Manchester City', season: '2015/16', rarity: 'gold', overall: 84,
    pace: 59, shooting: 33, passing: 36, dribbling: 41, defending: 88, physical: 74, composure: 69, vision: 42, traits: [], photoUrl: '/players/fifaindex-famous/150724.webp' },
  { id: 'albiol_napoli', shortName: 'Albiol', fullName: 'Raúl Albiol Tortajada', position: 'CB', nation: 'Espanha', club: 'Napoli', season: '2018/19', rarity: 'gold', overall: 84,
    pace: 53, shooting: 41, passing: 67, dribbling: 66, defending: 85, physical: 73, composure: 75, vision: 57, traits: [], photoUrl: '/players/fifaindex-famous/157481.webp' },
  { id: 'dembele_tottenham', shortName: 'M. Dembélé', fullName: 'Mousa Dembélé', position: 'CM', nation: 'Bélgica', club: 'Tottenham', season: '2017/18', rarity: 'gold', overall: 84,
    pace: 76, shooting: 72, passing: 82, dribbling: 85, defending: 75, physical: 81, composure: 90, vision: 80, traits: [], photoUrl: '/players/fifaindex-famous/162240.webp' },
  { id: 'khedira_juventus', shortName: 'Khedira', fullName: 'Sami Khedira', position: 'CM', nation: 'Alemanha', club: 'Juventus', season: '2018/19', rarity: 'gold', overall: 84,
    pace: 57, shooting: 76, passing: 82, dribbling: 74, defending: 80, physical: 78, composure: 84, vision: 80, traits: [], photoUrl: '/players/fifaindex-famous/179846.webp' },
  { id: 'strootman_roma', shortName: 'Strootman', fullName: 'Kevin Strootman', position: 'CM', nation: 'Holanda', club: 'Roma', season: '2016/17', rarity: 'gold', overall: 84,
    pace: 67, shooting: 75, passing: 84, dribbling: 77, defending: 76, physical: 76, composure: 85, vision: 84, traits: [], photoUrl: '/players/fifaindex-famous/189712.webp' },
  { id: 'canales_real_betis', shortName: 'Canales', fullName: 'Sergio Canales Madrazo', position: 'RM', nation: 'Espanha', club: 'Real Betis', season: '2022/23', rarity: 'gold', overall: 84,
    pace: 83, shooting: 78, passing: 86, dribbling: 83, defending: 65, physical: 65, composure: 80, vision: 90, traits: [], photoUrl: '/players/fifaindex-famous/190286.webp' },
  { id: 'glik_monaco', shortName: 'Glik', fullName: 'Kamil Glik', position: 'CB', nation: 'Polônia', club: 'Monaco', season: '2017/18', rarity: 'gold', overall: 84,
    pace: 55, shooting: 31, passing: 48, dribbling: 60, defending: 84, physical: 83, composure: 79, vision: 23, traits: [], photoUrl: '/players/fifaindex-famous/190547.webp' },
  { id: 'illarramendi_real_sociedad', shortName: 'Illarramendi', fullName: 'Asier Illarramendi', position: 'CDM', nation: 'Espanha', club: 'Real Sociedad', season: '2018/19', rarity: 'gold', overall: 84,
    pace: 61, shooting: 67, passing: 84, dribbling: 78, defending: 77, physical: 71, composure: 79, vision: 86, traits: [], photoUrl: '/players/fifaindex-famous/190584.webp' },
  { id: 'hradecky_bayer_leverkusen', shortName: 'Hrádecký', fullName: 'Lukáš Hrádecký', position: 'GK', nation: 'Finlândia', club: 'Bayer Leverkusen', season: '2018/19', rarity: 'gold', overall: 84,
    pace: 41, shooting: 13, passing: 29, dribbling: 41, defending: 88, physical: 74, composure: 48, vision: 53, traits: [], photoUrl: '/players/fifaindex-famous/190941.webp' },
  { id: 'ander_herrera_manchester_united', shortName: 'Ander Herrera', fullName: 'Ander Herrera Agüera', position: 'CM', nation: 'Espanha', club: 'Manchester United', season: '2016/17', rarity: 'gold', overall: 84,
    pace: 73, shooting: 73, passing: 84, dribbling: 84, defending: 73, physical: 76, composure: 82, vision: 86, traits: [], photoUrl: '/players/fifaindex-famous/191740.webp' },
  { id: 'cuadrado_juventus', shortName: 'Cuadrado', fullName: 'Juan Cuadrado', position: 'RM', nation: 'Colômbia', club: 'Juventus', season: '2018/19', rarity: 'gold', overall: 84,
    pace: 91, shooting: 74, passing: 75, dribbling: 85, defending: 65, physical: 73, composure: 80, vision: 76, traits: [], photoUrl: '/players/fifaindex-famous/193082.webp' },
  { id: 'baumann_hoffenheim', shortName: 'Baumann', fullName: 'Oliver Baumann', position: 'GK', nation: 'Alemanha', club: 'Hoffenheim', season: '2026/27', rarity: 'gold', overall: 84,
    pace: 39, shooting: 21, passing: 40, dribbling: 43, defending: 88, physical: 74, composure: 52, vision: 50, traits: [], photoUrl: '/players/fifaindex-famous/193698.webp' },
  { id: 'perin_juventus', shortName: 'Perin', fullName: 'Mattia Perin', position: 'GK', nation: 'Itália', club: 'Juventus', season: '2018/19', rarity: 'gold', overall: 84,
    pace: 56, shooting: 17, passing: 36, dribbling: 48, defending: 88, physical: 74, composure: 65, vision: 44, traits: [], photoUrl: '/players/fifaindex-famous/198009.webp' },
  { id: 'tadic_ajax', shortName: 'Tadić', fullName: 'Dušan Tadić', position: 'LW', nation: 'Sérvia', club: 'Ajax', season: '2021/22', rarity: 'gold', overall: 84,
    pace: 68, shooting: 82, passing: 85, dribbling: 83, defending: 44, physical: 71, composure: 86, vision: 88, traits: [], photoUrl: '/players/fifaindex-famous/199434.webp' },
  { id: 'ben_yedder_monaco', shortName: 'Ben Yedder', fullName: 'Wissam Ben Yedder', position: 'ST', nation: 'França', club: 'Monaco', season: '2022/23', rarity: 'gold', overall: 84,
    pace: 81, shooting: 84, passing: 76, dribbling: 88, defending: 42, physical: 70, composure: 85, vision: 80, traits: [], photoUrl: '/players/fifaindex-famous/199451.webp' },
  { id: 'digne_everton', shortName: 'Digne', fullName: 'Lucas Digne', position: 'LB', nation: 'França', club: 'Everton', season: '2020/21', rarity: 'gold', overall: 84,
    pace: 78, shooting: 70, passing: 76, dribbling: 80, defending: 80, physical: 81, composure: 81, vision: 75, traits: [], photoUrl: '/players/fifaindex-famous/200458.webp' },
  { id: 'morata_atletico_madrid', shortName: 'Morata', fullName: 'Álvaro Morata', position: 'ST', nation: 'Espanha', club: 'Atlético Madrid', season: '2023/24', rarity: 'gold', overall: 84,
    pace: 82, shooting: 82, passing: 72, dribbling: 77, defending: 37, physical: 81, composure: 79, vision: 77, traits: [], photoUrl: '/players/fifaindex-famous/201153.webp' },
  { id: 'draxler_paris_saint_germain', shortName: 'Draxler', fullName: 'Julian Draxler', position: 'LW', nation: 'Alemanha', club: 'Paris Saint-Germain', season: '2017/18', rarity: 'gold', overall: 84,
    pace: 77, shooting: 79, passing: 81, dribbling: 83, defending: 53, physical: 65, composure: 81, vision: 84, traits: [], photoUrl: '/players/fifaindex-famous/202166.webp' },
  { id: 'nick_pope_newcastle', shortName: 'Nick Pope', fullName: 'Nick Pope', position: 'GK', nation: 'Inglaterra', club: 'Newcastle', season: '2023/24', rarity: 'gold', overall: 84,
    pace: 48, shooting: 22, passing: 48, dribbling: 44, defending: 88, physical: 74, composure: 63, vision: 50, traits: [], photoUrl: '/players/fifaindex-famous/203841.webp' },
  { id: 'inigo_martinez_al_nassr', shortName: 'Iñigo Martínez', fullName: 'Iñigo Martínez', position: 'CB', nation: 'Espanha', club: 'Al Nassr', season: '2025/26', rarity: 'gold', overall: 84,
    pace: 71, shooting: 55, passing: 76, dribbling: 70, defending: 84, physical: 81, composure: 76, vision: 65, traits: [], photoUrl: '/players/fifaindex-famous/204525.webp' },
  { id: 'savic_atletico_madrid', shortName: 'Savić', fullName: 'Stefan Savić', position: 'CB', nation: 'Montenegro', club: 'Atlético Madrid', season: '2021/22', rarity: 'gold', overall: 84,
    pace: 63, shooting: 34, passing: 66, dribbling: 64, defending: 86, physical: 77, composure: 80, vision: 55, traits: [], photoUrl: '/players/fifaindex-famous/204639.webp' },
  { id: 'raul_jimenez_wolves', shortName: 'Raúl Jiménez', fullName: 'Raúl Jiménez', position: 'ST', nation: 'México', club: 'Wolves', season: '2020/21', rarity: 'gold', overall: 84,
    pace: 75, shooting: 83, passing: 78, dribbling: 79, defending: 52, physical: 82, composure: 81, vision: 78, traits: [], photoUrl: '/players/fifaindex-famous/204838.webp' },
  { id: 'kostic_eintracht_frankfurt', shortName: 'Kostić', fullName: 'Filip Kostić', position: 'LM', nation: 'Sérvia', club: 'Eintracht Frankfurt', season: '2021/22', rarity: 'gold', overall: 84,
    pace: 85, shooting: 76, passing: 78, dribbling: 81, defending: 66, physical: 79, composure: 80, vision: 81, traits: [], photoUrl: '/players/fifaindex-famous/208574.webp' },
  { id: 'martial_manchester_united', shortName: 'Martial', fullName: 'Anthony Martial', position: 'LW', nation: 'França', club: 'Manchester United', season: '2018/19', rarity: 'gold', overall: 84,
    pace: 88, shooting: 81, passing: 70, dribbling: 84, defending: 44, physical: 71, composure: 80, vision: 74, traits: [], photoUrl: '/players/fifaindex-famous/211300.webp' },
  { id: 'hojbjerg_tottenham', shortName: 'Højbjerg', fullName: 'Pierre-Emile Højbjerg', position: 'CDM', nation: 'Dinamarca', club: 'Tottenham', season: '2022/23', rarity: 'gold', overall: 84,
    pace: 55, shooting: 71, passing: 81, dribbling: 77, defending: 78, physical: 80, composure: 85, vision: 75, traits: [], photoUrl: '/players/fifaindex-famous/213648.webp' },
  { id: 'duvan_zapata_atalanta', shortName: 'Duván Zapata', fullName: 'Duván Zapata', position: 'ST', nation: 'Colômbia', club: 'Atalanta', season: '2021/22', rarity: 'gold', overall: 84,
    pace: 79, shooting: 80, passing: 62, dribbling: 75, defending: 39, physical: 81, composure: 82, vision: 66, traits: [], photoUrl: '/players/fifaindex-famous/215333.webp' },
  { id: 'asensio_real_madrid', shortName: 'Asensio', fullName: 'Marco Asensio Willemsen', position: 'LW', nation: 'Espanha', club: 'Real Madrid', season: '2018/19', rarity: 'gold', overall: 84,
    pace: 83, shooting: 80, passing: 82, dribbling: 82, defending: 45, physical: 60, composure: 83, vision: 82, traits: [], photoUrl: '/players/fifaindex-famous/220834.webp' },
  { id: 'locatelli_juventus', shortName: 'Locatelli', fullName: 'Manuel Locatelli', position: 'CDM', nation: 'Itália', club: 'Juventus', season: '2025/26', rarity: 'gold', overall: 84,
    pace: 63, shooting: 72, passing: 83, dribbling: 75, defending: 79, physical: 79, composure: 82, vision: 82, traits: [], photoUrl: '/players/fifaindex-famous/222077.webp' },
  { id: 'bennacer_milan', shortName: 'Bennacer', fullName: 'Ismaël Bennacer', position: 'CDM', nation: 'Argélia', club: 'Milan', season: '2023/24', rarity: 'gold', overall: 84,
    pace: 80, shooting: 73, passing: 83, dribbling: 86, defending: 77, physical: 80, composure: 87, vision: 81, traits: [], photoUrl: '/players/fifaindex-famous/226754.webp' },
  { id: 'ndidi_leicester_city', shortName: 'Ndidi', fullName: 'Wilfred Ndidi', position: 'CDM', nation: 'Nigéria', club: 'Leicester City', season: '2019/20', rarity: 'gold', overall: 84,
    pace: 71, shooting: 64, passing: 73, dribbling: 75, defending: 85, physical: 87, composure: 80, vision: 67, traits: [], photoUrl: '/players/fifaindex-famous/226790.webp' },
  { id: 'pavard_inter_milan', shortName: 'Pavard', fullName: 'Benjamin Pavard', position: 'CB', nation: 'França', club: 'Inter Milan', season: '2024/25', rarity: 'gold', overall: 84,
    pace: 75, shooting: 68, passing: 77, dribbling: 77, defending: 86, physical: 83, composure: 83, vision: 69, traits: [], photoUrl: '/players/fifaindex-famous/226851.webp' },
  { id: 'palhinha_fulham', shortName: 'Palhinha', fullName: 'João Palhinha', position: 'CDM', nation: 'Portugal', club: 'Fulham', season: '2023/24', rarity: 'gold', overall: 84,
    pace: 65, shooting: 66, passing: 77, dribbling: 74, defending: 84, physical: 90, composure: 84, vision: 72, traits: [], photoUrl: '/players/fifaindex-famous/229391.webp' },
  { id: 'mancini_roma', shortName: 'Mancini', fullName: 'Gianluca Mancini', position: 'CB', nation: 'Itália', club: 'Roma', season: '2026/27', rarity: 'gold', overall: 84,
    pace: 67, shooting: 48, passing: 68, dribbling: 67, defending: 84, physical: 83, composure: 83, vision: 56, traits: [], photoUrl: '/players/fifaindex-famous/229582.webp' },
  { id: 'kessie_barcelona', shortName: 'Kessié', fullName: 'Franck Kessié', position: 'CDM', nation: 'Costa do Marfim', club: 'Barcelona', season: '2022/23', rarity: 'gold', overall: 84,
    pace: 78, shooting: 76, passing: 78, dribbling: 79, defending: 80, physical: 84, composure: 84, vision: 76, traits: [], photoUrl: '/players/fifaindex-famous/230938.webp' },
  { id: 'ben_white_arsenal', shortName: 'Ben White', fullName: 'Ben White', position: 'RB', nation: 'Inglaterra', club: 'Arsenal', season: '2024/25', rarity: 'gold', overall: 84,
    pace: 72, shooting: 36, passing: 80, dribbling: 76, defending: 82, physical: 81, composure: 83, vision: 76, traits: [], photoUrl: '/players/fifaindex-famous/231936.webp' },
  { id: 'kamara_aston_villa', shortName: 'Kamara', fullName: 'Boubacar Kamara', position: 'CDM', nation: 'França', club: 'Aston Villa', season: '2025/26', rarity: 'gold', overall: 84,
    pace: 63, shooting: 55, passing: 82, dribbling: 78, defending: 82, physical: 80, composure: 85, vision: 79, traits: [], photoUrl: '/players/fifaindex-famous/236987.webp' },
  { id: 'lisandro_manchester_united', shortName: 'Lisandro', fullName: 'Lisandro Martínez', position: 'CB', nation: 'Argentina', club: 'Manchester United', season: '2023/24', rarity: 'gold', overall: 84,
    pace: 73, shooting: 60, passing: 80, dribbling: 81, defending: 83, physical: 83, composure: 87, vision: 76, traits: [], photoUrl: '/players/fifaindex-famous/239301.webp' },
  { id: 'vicario_tottenham', shortName: 'Vicario', fullName: 'Guglielmo Vicario', position: 'GK', nation: 'Itália', club: 'Tottenham', season: '2023/24', rarity: 'gold', overall: 84,
    pace: 51, shooting: 17, passing: 60, dribbling: 51, defending: 88, physical: 74, composure: 63, vision: 69, traits: [], photoUrl: '/players/fifaindex-famous/240091.webp' },
  { id: 'diaby_bayer_leverkusen', shortName: 'Diaby', fullName: 'Moussa Diaby', position: 'RM', nation: 'França', club: 'Bayer Leverkusen', season: '2022/23', rarity: 'gold', overall: 84,
    pace: 94, shooting: 69, passing: 76, dribbling: 85, defending: 41, physical: 64, composure: 75, vision: 77, traits: [], photoUrl: '/players/fifaindex-famous/241852.webp' },
  { id: 'timber_arsenal', shortName: 'J. Timber', fullName: 'Jurriën Timber', position: 'RB', nation: 'Holanda', club: 'Arsenal', season: '2026/27', rarity: 'gold', overall: 84,
    pace: 76, shooting: 51, passing: 77, dribbling: 79, defending: 83, physical: 80, composure: 82, vision: 77, traits: [], photoUrl: '/players/fifaindex-famous/251805.webp' },
  { id: 'nico_paz_como', shortName: 'Nico Paz', fullName: 'Nico Paz', position: 'CAM', nation: 'Argentina', club: 'Como', season: '2026/27', rarity: 'gold', overall: 84,
    pace: 81, shooting: 73, passing: 81, dribbling: 79, defending: 53, physical: 67, composure: 78, vision: 80, traits: [], photoUrl: '/players/fifaindex-famous/277846.webp' },
  { id: 'carrick_manchester_united', shortName: 'Carrick', fullName: 'Michael Carrick', position: 'CDM', nation: 'Inglaterra', club: 'Manchester United', season: '2016/17', rarity: 'gold', overall: 82,
    pace: 52, shooting: 68, passing: 85, dribbling: 74, defending: 76, physical: 69, composure: 85, vision: 85, traits: [], photoUrl: '/players/fifaindex-famous/21146.webp' },
  { id: 'pepe_reina_napoli', shortName: 'Pepe Reina', fullName: 'José Manuel Reina Páez', position: 'GK', nation: 'Espanha', club: 'Napoli', season: '2017/18', rarity: 'gold', overall: 83,
    pace: 56, shooting: 17, passing: 35, dribbling: 48, defending: 87, physical: 73, composure: 60, vision: 65, traits: [], photoUrl: '/players/fifaindex-famous/24630.webp' },
  { id: 'berbatov_monaco', shortName: 'Berbatov', fullName: 'Dimitar Berbatov', position: 'ST', nation: 'Bulgária', club: 'Monaco', season: '2014/15', rarity: 'gold', overall: 80,
    pace: 59, shooting: 82, passing: 81, dribbling: 73, defending: 37, physical: 60, composure: 78, vision: 82, traits: [], photoUrl: '/players/fifaindex-famous/30110.webp' },
  { id: 'rosicky_arsenal', shortName: 'Rosický', fullName: 'Tomáš Rosický', position: 'CAM', nation: 'República Tcheca', club: 'Arsenal', season: '2015/16', rarity: 'gold', overall: 81,
    pace: 75, shooting: 73, passing: 82, dribbling: 82, defending: 46, physical: 63, composure: 84, vision: 85, traits: [], photoUrl: '/players/fifaindex-famous/8473.webp' },
  { id: 'howedes_schalke', shortName: 'Höwedes', fullName: 'Benedikt Höwedes', position: 'CB', nation: 'Alemanha', club: 'Schalke', season: '2016/17', rarity: 'gold', overall: 84,
    pace: 64, shooting: 48, passing: 65, dribbling: 70, defending: 84, physical: 78, composure: 82, vision: 57, traits: [], photoUrl: '/players/fifaindex-famous/179784.webp' },
  { id: 'gaitan_atletico_madrid', shortName: 'Gaitán', fullName: 'Nicolás Gaitán', position: 'LM', nation: 'Argentina', club: 'Atlético Madrid', season: '2016/17', rarity: 'gold', overall: 84,
    pace: 82, shooting: 75, passing: 80, dribbling: 84, defending: 42, physical: 62, composure: 80, vision: 82, traits: [], photoUrl: '/players/fifaindex-famous/184144.webp' },
];
