import type { Player } from '../gameData';

/**
 * Versões em outros clubes de jogadores que já estão no catálogo (e alguns
 * nomes novos), FIFA 15 → FC 27, triadas no top 100 do fifaindex.com por nota.
 * Atributos e clube vêm da edição da carta; a foto é o rosto oficial (CDN do
 * sofifa, pelo ID EA) conferido pela camisa: quando a foto da edição ainda
 * mostrava o clube anterior, usou-se a da edição seguinte no mesmo clube, e as
 * versões sem nenhuma foto com a camisa certa ficaram de fora.
 */
export const FIFAINDEX_VERSION_ADDITIONS: Player[] = [
  { id: 'hazard_real_madrid_2019_20', shortName: 'Hazard', fullName: 'Eden Hazard', position: 'LW', nation: 'Bélgica', club: 'Real Madrid', season: '2019/20', rarity: 'legendary', overall: 91,
    pace: 91, shooting: 84, passing: 87, dribbling: 93, defending: 37, physical: 64, composure: 91, vision: 89, traits: [], photoUrl: '/players/fifaindex-versions/183277_21.webp' },
  { id: 'ibrahimovic_manchester_united_2016_17', shortName: 'Ibrahimović', fullName: 'Zlatan Ibrahimović', position: 'ST', nation: 'Suécia', club: 'Manchester United', season: '2016/17', rarity: 'legendary', overall: 90,
    pace: 70, shooting: 90, passing: 81, dribbling: 80, defending: 37, physical: 81, composure: 91, vision: 83, traits: [], photoUrl: '/players/fifaindex-versions/41236_17.webp' },
  { id: 'hummels_bayern_munich_2017_18', shortName: 'Hummels', fullName: 'Mats Hummels', position: 'CB', nation: 'Alemanha', club: 'Bayern Munich', season: '2017/18', rarity: 'legendary', overall: 90,
    pace: 65, shooting: 60, passing: 82, dribbling: 75, defending: 90, physical: 72, composure: 91, vision: 79, traits: [], photoUrl: '/players/fifaindex-versions/178603_18.webp' },
  { id: 'courtois_chelsea_2016_17', shortName: 'Courtois', fullName: 'Thibaut Courtois', position: 'GK', nation: 'Bélgica', club: 'Chelsea', season: '2016/17', rarity: 'legendary', overall: 89,
    pace: 49, shooting: 20, passing: 35, dribbling: 46, defending: 93, physical: 68, composure: 52, vision: 44, traits: [], photoUrl: '/players/fifaindex-versions/192119_17.webp' },
  { id: 'k_navas_psg_2020_21', shortName: 'K. Navas', fullName: 'Keylor Navas', position: 'GK', nation: 'Costa Rica', club: 'PSG', season: '2020/21', rarity: 'legendary', overall: 89,
    pace: 53, shooting: 23, passing: 45, dribbling: 52, defending: 93, physical: 74, composure: 67, vision: 68, traits: [], photoUrl: '/players/fifaindex-versions/193041_21.webp' },
  { id: 'griezmann_barcelona_2019_20', shortName: 'Griezmann', fullName: 'Antoine Griezmann', position: 'ST', nation: 'França', club: 'Barcelona', season: '2019/20', rarity: 'legendary', overall: 89,
    pace: 80, shooting: 86, passing: 84, dribbling: 89, defending: 59, physical: 78, composure: 89, vision: 86, traits: [], photoUrl: '/players/fifaindex-versions/194765_20.webp' },
  { id: 'casemiro_manchester_united_2022_23', shortName: 'Casemiro', fullName: 'Carlos Henrique Casimiro', position: 'CDM', nation: 'Brasil', club: 'Manchester United', season: '2022/23', rarity: 'legendary', overall: 89,
    pace: 63, shooting: 73, passing: 82, dribbling: 75, defending: 88, physical: 89, composure: 85, vision: 79, traits: [], photoUrl: '/players/fifaindex-versions/200145_23.webp' },
  { id: 'donnarumma_manchester_city_2025_26', shortName: 'Donnarumma', fullName: 'Gianluigi Donnarumma', position: 'GK', nation: 'Itália', club: 'Manchester City', season: '2025/26', rarity: 'legendary', overall: 89,
    pace: 52, shooting: 22, passing: 46, dribbling: 49, defending: 93, physical: 73, composure: 54, vision: 60, traits: [], photoUrl: '/players/fifaindex-versions/230621_26.webp' },
  { id: 'cech_arsenal_2016_17', shortName: 'Čech', fullName: 'Petr Čech', position: 'GK', nation: 'República Tcheca', club: 'Arsenal', season: '2016/17', rarity: 'legendary', overall: 88,
    pace: 42, shooting: 16, passing: 40, dribbling: 46, defending: 92, physical: 51, composure: 70, vision: 53, traits: [], photoUrl: '/players/fifaindex-versions/48940_17.webp' },
  { id: 'benzema_al_ittihad_2023_24', shortName: 'Benzema', fullName: 'Karim Mostafa Benzema', position: 'ST', nation: 'França', club: 'Al Ittihad', season: '2023/24', rarity: 'legendary', overall: 88,
    pace: 76, shooting: 84, passing: 84, dribbling: 84, defending: 43, physical: 77, composure: 88, vision: 88, traits: [], photoUrl: '/players/fifaindex-versions/165153_24.webp' },
  { id: 'neymar_al_hilal_2023_24', shortName: 'Neymar', fullName: 'Neymar da Silva Santos Júnior', position: 'LW', nation: 'Brasil', club: 'Al Hilal', season: '2023/24', rarity: 'legendary', overall: 88,
    pace: 83, shooting: 83, passing: 84, dribbling: 90, defending: 39, physical: 65, composure: 93, vision: 87, traits: [], photoUrl: '/players/fifaindex-versions/190871_24.webp' },
  { id: 'donnarumma_psg_2021_22', shortName: 'Donnarumma', fullName: 'Gianluigi Donnarumma', position: 'GK', nation: 'Itália', club: 'PSG', season: '2021/22', rarity: 'legendary', overall: 88,
    pace: 52, shooting: 23, passing: 43, dribbling: 52, defending: 92, physical: 72, composure: 65, vision: 60, traits: [], photoUrl: '/players/fifaindex-versions/230621_22.webp' },
  { id: 'aguero_barcelona_2021_22', shortName: 'Agüero', fullName: 'Sergio Leonel Agüero', position: 'ST', nation: 'Argentina', club: 'Barcelona', season: '2021/22', rarity: 'gold', overall: 87,
    pace: 71, shooting: 86, passing: 74, dribbling: 88, defending: 37, physical: 69, composure: 91, vision: 80, traits: [], photoUrl: '/players/fifaindex-versions/153079_22.webp' },
  { id: 'sommer_inter_milan_2024_25', shortName: 'Sommer', fullName: 'Yann Sommer', position: 'GK', nation: 'Suíça', club: 'Inter Milan', season: '2024/25', rarity: 'gold', overall: 87,
    pace: 51, shooting: 23, passing: 49, dribbling: 51, defending: 91, physical: 68, composure: 54, vision: 64, traits: [], photoUrl: '/players/fifaindex-versions/177683_25.webp' },
  { id: 'vidal_bayern_munich_2016_17', shortName: 'Vidal', fullName: 'Arturo Vidal', position: 'CM', nation: 'Chile', club: 'Bayern Munich', season: '2016/17', rarity: 'gold', overall: 87,
    pace: 75, shooting: 81, passing: 82, dribbling: 81, defending: 84, physical: 86, composure: 86, vision: 80, traits: [], photoUrl: '/players/fifaindex-versions/181872_17.webp' },
  { id: 'aubameyang_borussia_dortmund_2016_17', shortName: 'Aubameyang', fullName: 'Pierre-Emerick Aubameyang', position: 'ST', nation: 'Gabão', club: 'Borussia Dortmund', season: '2016/17', rarity: 'gold', overall: 87,
    pace: 95, shooting: 84, passing: 72, dribbling: 80, defending: 43, physical: 69, composure: 79, vision: 77, traits: [], photoUrl: '/players/fifaindex-versions/188567_17.webp' },
  { id: 'parejo_valencia_2019_20', shortName: 'Parejo', fullName: 'Daniel Parejo Muñoz', position: 'CM', nation: 'Espanha', club: 'Valencia', season: '2019/20', rarity: 'gold', overall: 87,
    pace: 42, shooting: 82, passing: 88, dribbling: 79, defending: 70, physical: 65, composure: 85, vision: 86, traits: [], photoUrl: '/players/fifaindex-versions/189513_20.webp' },
  { id: 'eriksen_inter_milan_2019_20', shortName: 'Eriksen', fullName: 'Christian Eriksen', position: 'CAM', nation: 'Dinamarca', club: 'Inter Milan', season: '2019/20', rarity: 'gold', overall: 87,
    pace: 73, shooting: 80, passing: 89, dribbling: 84, defending: 49, physical: 61, composure: 88, vision: 90, traits: [], photoUrl: '/players/fifaindex-versions/190460_21.webp' },
  { id: 'de_bruyne_napoli_2025_26', shortName: 'De Bruyne', fullName: 'Kevin De Bruyne', position: 'CM', nation: 'Bélgica', club: 'Napoli', season: '2025/26', rarity: 'gold', overall: 87,
    pace: 65, shooting: 83, passing: 92, dribbling: 81, defending: 62, physical: 71, composure: 87, vision: 92, traits: [], photoUrl: '/players/fifaindex-versions/192985_27.webp' },
  { id: 'isco_real_madrid_2018_19', shortName: 'Isco', fullName: 'Francisco Román Alarcón Suárez', position: 'CAM', nation: 'Espanha', club: 'Real Madrid', season: '2018/19', rarity: 'gold', overall: 87,
    pace: 72, shooting: 75, passing: 84, dribbling: 88, defending: 59, physical: 61, composure: 86, vision: 86, traits: [], photoUrl: '/players/fifaindex-versions/197781_19.webp' },
  { id: 'james_bayern_munich_2017_18', shortName: 'James', fullName: 'James Rodríguez', position: 'CAM', nation: 'Colômbia', club: 'Bayern Munich', season: '2017/18', rarity: 'gold', overall: 87,
    pace: 72, shooting: 85, passing: 85, dribbling: 84, defending: 46, physical: 64, composure: 87, vision: 88, traits: [], photoUrl: '/players/fifaindex-versions/198710_18.webp' },
  { id: 'fabinho_liverpool_2020_21', shortName: 'Fabinho', fullName: 'Fábio Henrique Tavares', position: 'CDM', nation: 'Brasil', club: 'Liverpool', season: '2020/21', rarity: 'gold', overall: 87,
    pace: 68, shooting: 70, passing: 82, dribbling: 77, defending: 85, physical: 83, composure: 84, vision: 79, traits: [], photoUrl: '/players/fifaindex-versions/209499_21.webp' },
  { id: 'tah_bayer_leverkusen_2024_25', shortName: 'Tah', fullName: 'Jonathan Tah', position: 'CB', nation: 'Alemanha', club: 'Bayer Leverkusen', season: '2024/25', rarity: 'gold', overall: 87,
    pace: 69, shooting: 41, passing: 67, dribbling: 64, defending: 86, physical: 83, composure: 79, vision: 57, traits: [], photoUrl: '/players/fifaindex-versions/213331_25.webp' },
  { id: 'osimhen_napoli_2023_24', shortName: 'Osimhen', fullName: 'Victor Osimhen', position: 'ST', nation: 'Nigéria', club: 'Napoli', season: '2023/24', rarity: 'gold', overall: 87,
    pace: 89, shooting: 83, passing: 65, dribbling: 80, defending: 44, physical: 82, composure: 80, vision: 70, traits: [], photoUrl: '/players/fifaindex-versions/232293_24.webp' },
  { id: 'wirtz_liverpool_2025_26', shortName: 'Wirtz', fullName: 'Florian Wirtz', position: 'CAM', nation: 'Alemanha', club: 'Liverpool', season: '2025/26', rarity: 'gold', overall: 87,
    pace: 80, shooting: 79, passing: 87, dribbling: 87, defending: 51, physical: 69, composure: 86, vision: 89, traits: [], photoUrl: '/players/fifaindex-versions/256630_27.webp' },
  { id: 'fabregas_chelsea_2015_16', shortName: 'Fàbregas', fullName: 'Cesc Fàbregas Soler', position: 'CM', nation: 'Espanha', club: 'Chelsea', season: '2015/16', rarity: 'gold', overall: 86,
    pace: 63, shooting: 79, passing: 91, dribbling: 79, defending: 63, physical: 65, composure: 83, vision: 92, traits: [], photoUrl: '/players/fifaindex-versions/162895_16.webp' },
  { id: 'filipe_luis_atletico_madrid_2017_18', shortName: 'Filipe Luís', fullName: 'Filipe Luís Kasmirski', position: 'LB', nation: 'Brasil', club: 'Atlético Madrid', season: '2017/18', rarity: 'gold', overall: 86,
    pace: 80, shooting: 64, passing: 75, dribbling: 77, defending: 82, physical: 79, composure: 88, vision: 70, traits: [], photoUrl: '/players/fifaindex-versions/164169_18.webp' },
  { id: 'falcao_monaco_2014_15', shortName: 'Falcao', fullName: 'Radamel Falcao García Zárate', position: 'ST', nation: 'Colômbia', club: 'Monaco', season: '2014/15', rarity: 'gold', overall: 86,
    pace: 74, shooting: 84, passing: 63, dribbling: 82, defending: 45, physical: 77, composure: 80, vision: 68, traits: [], photoUrl: '/players/fifaindex-versions/167397_15.webp' },
  { id: 'higuain_napoli_2015_16', shortName: 'Higuaín', fullName: 'Gonzalo Higuaín', position: 'ST', nation: 'Argentina', club: 'Napoli', season: '2015/16', rarity: 'gold', overall: 86,
    pace: 81, shooting: 83, passing: 66, dribbling: 78, defending: 30, physical: 70, composure: 86, vision: 70, traits: [], photoUrl: '/players/fifaindex-versions/167664_16.webp' },
  { id: 'd_silva_real_sociedad_2020_21', shortName: 'D. Silva', fullName: 'David Silva', position: 'CAM', nation: 'Espanha', club: 'Real Sociedad', season: '2020/21', rarity: 'gold', overall: 86,
    pace: 64, shooting: 77, passing: 89, dribbling: 88, defending: 49, physical: 59, composure: 92, vision: 91, traits: [], photoUrl: '/players/fifaindex-versions/168542_22.webp' },
  { id: 'sommer_borussia_m_gladbach_2019_20', shortName: 'Sommer', fullName: 'Yann Sommer', position: 'GK', nation: 'Suíça', club: 'Borussia M\'gladbach', season: '2019/20', rarity: 'gold', overall: 86,
    pace: 51, shooting: 22, passing: 43, dribbling: 49, defending: 90, physical: 73, composure: 57, vision: 58, traits: [], photoUrl: '/players/fifaindex-versions/177683_20.webp' },
  { id: 'diego_costa_chelsea_2016_17', shortName: 'Diego Costa', fullName: 'Diego da Silva Costa', position: 'ST', nation: 'Espanha', club: 'Chelsea', season: '2016/17', rarity: 'gold', overall: 86,
    pace: 77, shooting: 82, passing: 64, dribbling: 74, defending: 45, physical: 83, composure: 84, vision: 74, traits: [], photoUrl: '/players/fifaindex-versions/179844_17.webp' },
  { id: 'thiago_liverpool_2021_22', shortName: 'Thiago', fullName: 'Thiago Alcântara', position: 'CM', nation: 'Espanha', club: 'Liverpool', season: '2021/22', rarity: 'gold', overall: 86,
    pace: 63, shooting: 75, passing: 89, dribbling: 89, defending: 70, physical: 74, composure: 90, vision: 88, traits: [], photoUrl: '/players/fifaindex-versions/189509_22.webp' },
  { id: 'lukaku_manchester_united_2017_18', shortName: 'Lukaku', fullName: 'Romelu Lukaku Menama', position: 'ST', nation: 'Bélgica', club: 'Manchester United', season: '2017/18', rarity: 'gold', overall: 86,
    pace: 83, shooting: 83, passing: 73, dribbling: 71, defending: 40, physical: 79, composure: 82, vision: 74, traits: [], photoUrl: '/players/fifaindex-versions/192505_18.webp' },
  { id: 'lukaku_chelsea_2021_22', shortName: 'Lukaku', fullName: 'Romelu Lukaku Menama', position: 'ST', nation: 'Bélgica', club: 'Chelsea', season: '2021/22', rarity: 'gold', overall: 86,
    pace: 81, shooting: 84, passing: 74, dribbling: 73, defending: 43, physical: 77, composure: 82, vision: 75, traits: [], photoUrl: '/players/fifaindex-versions/192505_22.webp' },
  { id: 'mkhitaryan_manchester_united_2016_17', shortName: 'Mkhitaryan', fullName: 'Henrikh Mkhitaryan', position: 'RM', nation: 'Armênia', club: 'Manchester United', season: '2016/17', rarity: 'gold', overall: 86,
    pace: 86, shooting: 79, passing: 81, dribbling: 83, defending: 56, physical: 72, composure: 67, vision: 85, traits: [], photoUrl: '/players/fifaindex-versions/192883_17.webp' },
  { id: 'k_navas_nottingham_forest_2022_23', shortName: 'K. Navas', fullName: 'Keylor Navas', position: 'GK', nation: 'Costa Rica', club: 'Nottingham Forest', season: '2022/23', rarity: 'gold', overall: 86,
    pace: 53, shooting: 23, passing: 47, dribbling: 53, defending: 90, physical: 70, composure: 63, vision: 64, traits: [], photoUrl: '/players/fifaindex-versions/193041_23.webp' },
  { id: 'pogba_juventus_2015_16', shortName: 'Pogba', fullName: 'Paul Pogba', position: 'CM', nation: 'França', club: 'Juventus', season: '2015/16', rarity: 'gold', overall: 86,
    pace: 77, shooting: 83, passing: 84, dribbling: 80, defending: 73, physical: 85, composure: 86, vision: 86, traits: [], photoUrl: '/players/fifaindex-versions/195864_16.webp' },
  { id: 'alaba_real_madrid_2022_23', shortName: 'Alaba', fullName: 'David Alaba', position: 'CB', nation: 'Áustria', club: 'Real Madrid', season: '2022/23', rarity: 'gold', overall: 86,
    pace: 79, shooting: 74, passing: 82, dribbling: 82, defending: 84, physical: 78, composure: 85, vision: 78, traits: [], photoUrl: '/players/fifaindex-versions/197445_23.webp' },
  { id: 'mahrez_al_ahli_2023_24', shortName: 'Mahrez', fullName: 'Riyad Mahrez', position: 'RM', nation: 'Argélia', club: 'Al Ahli', season: '2023/24', rarity: 'gold', overall: 86,
    pace: 79, shooting: 80, passing: 80, dribbling: 87, defending: 39, physical: 63, composure: 81, vision: 84, traits: [], photoUrl: '/players/fifaindex-versions/204485_24.webp' },
  { id: 'rudiger_chelsea_2021_22', shortName: 'Rüdiger', fullName: 'Antonio Rüdiger', position: 'CB', nation: 'Alemanha', club: 'Chelsea', season: '2021/22', rarity: 'gold', overall: 86,
    pace: 79, shooting: 51, passing: 73, dribbling: 68, defending: 85, physical: 84, composure: 78, vision: 61, traits: [], photoUrl: '/players/fifaindex-versions/205452_22.webp' },
  { id: 'dybala_roma_2022_23', shortName: 'Dybala', fullName: 'Paulo Bruno Exequiel Dybala', position: 'ST', nation: 'Argentina', club: 'Roma', season: '2022/23', rarity: 'gold', overall: 86,
    pace: 80, shooting: 86, passing: 85, dribbling: 87, defending: 42, physical: 63, composure: 79, vision: 91, traits: [], photoUrl: '/players/fifaindex-versions/211110_23.webp' },
  { id: 'l_sane_manchester_city_2018_19', shortName: 'L. Sané', fullName: 'Leroy Sané', position: 'LW', nation: 'Alemanha', club: 'Manchester City', season: '2018/19', rarity: 'gold', overall: 86,
    pace: 94, shooting: 81, passing: 75, dribbling: 84, defending: 42, physical: 69, composure: 80, vision: 82, traits: [], photoUrl: '/players/fifaindex-versions/222492_19.webp' },
  { id: 'milinkovic_savic_al_hilal_2023_24', shortName: 'Milinković-Savić', fullName: 'Sergej Milinković-Savić', position: 'CM', nation: 'Sérvia', club: 'Al Hilal', season: '2023/24', rarity: 'gold', overall: 86,
    pace: 64, shooting: 77, passing: 85, dribbling: 78, defending: 80, physical: 86, composure: 84, vision: 83, traits: [], photoUrl: '/players/fifaindex-versions/223848_24.webp' },
  { id: 'kvaratskhelia_napoli_2023_24', shortName: 'Kvaratskhelia', fullName: 'Khvicha Kvaratskhelia', position: 'LW', nation: 'Geórgia', club: 'Napoli', season: '2023/24', rarity: 'gold', overall: 86,
    pace: 85, shooting: 76, passing: 81, dribbling: 84, defending: 43, physical: 72, composure: 79, vision: 86, traits: [], photoUrl: '/players/fifaindex-versions/247635_24.webp' },
  { id: 'van_persie_manchester_united_2014_15', shortName: 'Van Persie', fullName: 'Robin van Persie', position: 'ST', nation: 'Holanda', club: 'Manchester United', season: '2014/15', rarity: 'gold', overall: 85,
    pace: 68, shooting: 87, passing: 79, dribbling: 78, defending: 37, physical: 65, composure: 86, vision: 82, traits: [], photoUrl: '/players/fifaindex-versions/7826_15.webp' },
  { id: 'ibrahimovic_la_galaxy_2017_18', shortName: 'Ibrahimović', fullName: 'Zlatan Ibrahimović', position: 'ST', nation: 'Suécia', club: 'LA Galaxy', season: '2017/18', rarity: 'gold', overall: 85,
    pace: 58, shooting: 86, passing: 77, dribbling: 75, defending: 41, physical: 75, composure: 90, vision: 79, traits: [], photoUrl: '/players/fifaindex-versions/41236_19.webp' },
  { id: 'x_alonso_bayern_munich_2014_15', shortName: 'X. Alonso', fullName: 'Xabi Alonso Olano', position: 'CDM', nation: 'Espanha', club: 'Bayern Munich', season: '2014/15', rarity: 'gold', overall: 85,
    pace: 48, shooting: 75, passing: 90, dribbling: 76, defending: 76, physical: 66, composure: 86, vision: 88, traits: [], photoUrl: '/players/fifaindex-versions/45197_15.webp' },
  { id: 'pepe_besiktas_2017_18', shortName: 'Pepe', fullName: 'Képler Laveran de Lima Ferreira', position: 'CB', nation: 'Portugal', club: 'Beşiktaş', season: '2017/18', rarity: 'gold', overall: 85,
    pace: 67, shooting: 48, passing: 59, dribbling: 66, defending: 83, physical: 79, composure: 79, vision: 48, traits: [], photoUrl: '/players/fifaindex-versions/120533_18.webp' },
  { id: 'schweini_manchester_united_2015_16', shortName: 'Schweini', fullName: 'Bastian Schweinsteiger', position: 'CM', nation: 'Alemanha', club: 'Manchester United', season: '2015/16', rarity: 'gold', overall: 85,
    pace: 52, shooting: 81, passing: 86, dribbling: 76, defending: 77, physical: 79, composure: 89, vision: 86, traits: [], photoUrl: '/players/fifaindex-versions/121944_17.webp' },
  { id: 'tevez_juventus_2014_15', shortName: 'Tevez', fullName: 'Carlos Alberto Tevez', position: 'ST', nation: 'Argentina', club: 'Juventus', season: '2014/15', rarity: 'gold', overall: 85,
    pace: 86, shooting: 86, passing: 76, dribbling: 88, defending: 46, physical: 83, composure: 90, vision: 83, traits: [], photoUrl: '/players/fifaindex-versions/143001_15.webp' },
  { id: 'tevez_boca_juniors_2015_16', shortName: 'Tevez', fullName: 'Carlos Alberto Tevez', position: 'ST', nation: 'Argentina', club: 'Boca Juniors', season: '2015/16', rarity: 'gold', overall: 85,
    pace: 88, shooting: 87, passing: 73, dribbling: 88, defending: 47, physical: 83, composure: 91, vision: 80, traits: [], photoUrl: '/players/fifaindex-versions/143001_16.webp' },
  { id: 'cazorla_arsenal_2014_15', shortName: 'Cazorla', fullName: 'Santiago Cazorla González', position: 'CAM', nation: 'Espanha', club: 'Arsenal', season: '2014/15', rarity: 'gold', overall: 85,
    pace: 73, shooting: 78, passing: 85, dribbling: 87, defending: 54, physical: 63, composure: 85, vision: 85, traits: [], photoUrl: '/players/fifaindex-versions/146562_15.webp' },
  { id: 'ruffier_saint_etienne_2016_17', shortName: 'Ruffier', fullName: 'Stéphane Ruffier', position: 'GK', nation: 'França', club: 'Saint-Étienne', season: '2016/17', rarity: 'gold', overall: 85,
    pace: 47, shooting: 16, passing: 38, dribbling: 45, defending: 89, physical: 72, composure: 57, vision: 49, traits: [], photoUrl: '/players/fifaindex-versions/167628_17.webp' },
  { id: 'matuidi_psg_2016_17', shortName: 'Matuidi', fullName: 'Blaise Matuidi', position: 'CDM', nation: 'França', club: 'PSG', season: '2016/17', rarity: 'gold', overall: 85,
    pace: 79, shooting: 67, passing: 79, dribbling: 79, defending: 81, physical: 85, composure: 85, vision: 75, traits: [], photoUrl: '/players/fifaindex-versions/170890_17.webp' },
  { id: 'sokratis_borussia_dortmund_2016_17', shortName: 'Sokratis', fullName: 'Sokratis Papastathopoulos', position: 'CB', nation: 'Grécia', club: 'Borussia Dortmund', season: '2016/17', rarity: 'gold', overall: 85,
    pace: 78, shooting: 51, passing: 60, dribbling: 68, defending: 85, physical: 84, composure: 82, vision: 52, traits: [], photoUrl: '/players/fifaindex-versions/172879_17.webp' },
  { id: 'modric_milan_2025_26', shortName: 'Modric', fullName: 'Luka Modrić', position: 'CM', nation: 'Croácia', club: 'Milan', season: '2025/26', rarity: 'gold', overall: 85,
    pace: 68, shooting: 77, passing: 88, dribbling: 87, defending: 71, physical: 65, composure: 91, vision: 88, traits: [], photoUrl: '/players/fifaindex-versions/177003_27.webp' },
  { id: 'payet_west_ham_2016_17', shortName: 'Payet', fullName: 'Dimitri Payet', position: 'LM', nation: 'França', club: 'West Ham', season: '2016/17', rarity: 'gold', overall: 85,
    pace: 77, shooting: 79, passing: 85, dribbling: 84, defending: 40, physical: 64, composure: 86, vision: 87, traits: [], photoUrl: '/players/fifaindex-versions/177388_17.webp' },
  { id: 'nainggolan_inter_milan_2018_19', shortName: 'Nainggolan', fullName: 'Radja Nainggolan', position: 'CM', nation: 'Bélgica', club: 'Inter Milan', season: '2018/19', rarity: 'gold', overall: 85,
    pace: 75, shooting: 78, passing: 80, dribbling: 82, defending: 81, physical: 84, composure: 84, vision: 76, traits: [], photoUrl: '/players/fifaindex-versions/178518_19.webp' },
  { id: 'vidal_juventus_2014_15', shortName: 'Vidal', fullName: 'Arturo Vidal', position: 'CM', nation: 'Chile', club: 'Juventus', season: '2014/15', rarity: 'gold', overall: 85,
    pace: 79, shooting: 80, passing: 81, dribbling: 81, defending: 81, physical: 85, composure: 84, vision: 80, traits: [], photoUrl: '/players/fifaindex-versions/181872_15.webp' },
  { id: 'di_maria_manchester_united_2014_15', shortName: 'Di María', fullName: 'Ángel Fabián Di María Hernández', position: 'CAM', nation: 'Argentina', club: 'Manchester United', season: '2014/15', rarity: 'gold', overall: 85,
    pace: 88, shooting: 79, passing: 81, dribbling: 84, defending: 52, physical: 73, composure: 89, vision: 83, traits: [], photoUrl: '/players/fifaindex-versions/183898_15.webp' },
  { id: 'szczesny_barcelona_2024_25', shortName: 'Szczęsny', fullName: 'Wojciech Szczęsny', position: 'GK', nation: 'Polônia', club: 'Barcelona', season: '2024/25', rarity: 'gold', overall: 85,
    pace: 47, shooting: 21, passing: 55, dribbling: 47, defending: 89, physical: 69, composure: 65, vision: 48, traits: [], photoUrl: '/players/fifaindex-versions/186153_25.webp' },
  { id: 'paulinho_guangzhou_evergrande_2019_20', shortName: 'Paulinho', fullName: 'José Paulo Bezerra Maciel Júnior', position: 'CM', nation: 'Brasil', club: 'Guangzhou Evergrande', season: '2019/20', rarity: 'gold', overall: 85,
    pace: 72, shooting: 80, passing: 81, dribbling: 80, defending: 80, physical: 87, composure: 81, vision: 84, traits: [], photoUrl: '/players/fifaindex-versions/187961_20.webp' },
  { id: 'aubameyang_barcelona_2021_22', shortName: 'Aubameyang', fullName: 'Pierre-Emerick Aubameyang', position: 'ST', nation: 'Gabão', club: 'Barcelona', season: '2021/22', rarity: 'gold', overall: 85,
    pace: 86, shooting: 83, passing: 72, dribbling: 78, defending: 42, physical: 67, composure: 83, vision: 74, traits: [], photoUrl: '/players/fifaindex-versions/188567_22.webp' },
  { id: 'mario_gotze_bayern_munich_2014_15', shortName: 'Mario Götze', fullName: 'Mario Götze', position: 'CAM', nation: 'Alemanha', club: 'Bayern Munich', season: '2014/15', rarity: 'gold', overall: 85,
    pace: 77, shooting: 75, passing: 82, dribbling: 88, defending: 38, physical: 63, composure: 87, vision: 85, traits: [], photoUrl: '/players/fifaindex-versions/192318_15.webp' },
  { id: 'otamendi_manchester_city_2017_18', shortName: 'Otamendi', fullName: 'Nicolás Otamendi', position: 'CB', nation: 'Argentina', club: 'Manchester City', season: '2017/18', rarity: 'gold', overall: 85,
    pace: 63, shooting: 55, passing: 65, dribbling: 69, defending: 85, physical: 84, composure: 84, vision: 48, traits: [], photoUrl: '/players/fifaindex-versions/192366_18.webp' },
  { id: 'lukaku_everton_2016_17', shortName: 'Lukaku', fullName: 'Romelu Lukaku Menama', position: 'ST', nation: 'Bélgica', club: 'Everton', season: '2016/17', rarity: 'gold', overall: 85,
    pace: 85, shooting: 82, passing: 69, dribbling: 71, defending: 40, physical: 79, composure: 84, vision: 70, traits: [], photoUrl: '/players/fifaindex-versions/192505_17.webp' },
  { id: 'leno_arsenal_2019_20', shortName: 'Leno', fullName: 'Bernd Leno', position: 'GK', nation: 'Alemanha', club: 'Arsenal', season: '2019/20', rarity: 'gold', overall: 85,
    pace: 55, shooting: 20, passing: 51, dribbling: 49, defending: 89, physical: 73, composure: 66, vision: 56, traits: [], photoUrl: '/players/fifaindex-versions/192563_20.webp' },
  { id: 'mkhitaryan_borussia_dortmund_2015_16', shortName: 'Mkhitaryan', fullName: 'Henrikh Mkhitaryan', position: 'RM', nation: 'Armênia', club: 'Borussia Dortmund', season: '2015/16', rarity: 'gold', overall: 85,
    pace: 85, shooting: 80, passing: 83, dribbling: 87, defending: 56, physical: 73, composure: 85, vision: 87, traits: [], photoUrl: '/players/fifaindex-versions/192883_16.webp' },
  { id: 'de_gea_fiorentina_2024_25', shortName: 'De Gea', fullName: 'David de Gea', position: 'GK', nation: 'Espanha', club: 'Fiorentina', season: '2024/25', rarity: 'gold', overall: 85,
    pace: 46, shooting: 21, passing: 39, dribbling: 47, defending: 89, physical: 57, composure: 45, vision: 38, traits: [], photoUrl: '/players/fifaindex-versions/193080_25.webp' },
  { id: 'lacazette_lyon_2016_17', shortName: 'Lacazette', fullName: 'Alexandre Lacazette', position: 'ST', nation: 'França', club: 'Lyon', season: '2016/17', rarity: 'gold', overall: 85,
    pace: 85, shooting: 83, passing: 75, dribbling: 85, defending: 41, physical: 76, composure: 86, vision: 77, traits: [], photoUrl: '/players/fifaindex-versions/193301_17.webp' },
  { id: 'xhaka_sunderland_2025_26', shortName: 'Xhaka', fullName: 'Granit Xhaka', position: 'CDM', nation: 'Suíça', club: 'Sunderland', season: '2025/26', rarity: 'gold', overall: 85,
    pace: 46, shooting: 73, passing: 88, dribbling: 73, defending: 77, physical: 81, composure: 85, vision: 85, traits: [], photoUrl: '/players/fifaindex-versions/199503_26.webp' },
  { id: 'varane_manchester_united_2021_22', shortName: 'Varane', fullName: 'Raphaël Varane', position: 'CB', nation: 'França', club: 'Manchester United', season: '2021/22', rarity: 'gold', overall: 85,
    pace: 82, shooting: 49, passing: 70, dribbling: 67, defending: 86, physical: 79, composure: 82, vision: 59, traits: [], photoUrl: '/players/fifaindex-versions/201535_22.webp' },
  { id: 'memphis_depay_barcelona_2021_22', shortName: 'Memphis Depay', fullName: 'Memphis Depay', position: 'ST', nation: 'Holanda', club: 'Barcelona', season: '2021/22', rarity: 'gold', overall: 85,
    pace: 83, shooting: 82, passing: 80, dribbling: 83, defending: 33, physical: 76, composure: 80, vision: 85, traits: [], photoUrl: '/players/fifaindex-versions/202556_22.webp' },
  { id: 'sterling_chelsea_2022_23', shortName: 'Sterling', fullName: 'Raheem Sterling', position: 'LW', nation: 'Inglaterra', club: 'Chelsea', season: '2022/23', rarity: 'gold', overall: 85,
    pace: 86, shooting: 77, passing: 75, dribbling: 87, defending: 45, physical: 65, composure: 77, vision: 80, traits: [], photoUrl: '/players/fifaindex-versions/202652_23.webp' },
  { id: 'carrasco_atletico_madrid_2017_18', shortName: 'Carrasco', fullName: 'Yannick Carrasco', position: 'LM', nation: 'Bélgica', club: 'Atlético Madrid', season: '2017/18', rarity: 'gold', overall: 85,
    pace: 88, shooting: 77, passing: 75, dribbling: 83, defending: 31, physical: 65, composure: 75, vision: 74, traits: [], photoUrl: '/players/fifaindex-versions/208418_18.webp' },
  { id: 'saul_atletico_madrid_2018_19', shortName: 'Saúl', fullName: 'Saúl Ñíguez', position: 'CM', nation: 'Espanha', club: 'Atlético Madrid', season: '2018/19', rarity: 'gold', overall: 85,
    pace: 73, shooting: 76, passing: 83, dribbling: 79, defending: 78, physical: 78, composure: 83, vision: 82, traits: [], photoUrl: '/players/fifaindex-versions/208421_19.webp' },
  { id: 'bono_al_hilal_2023_24', shortName: 'Bono', fullName: 'Yassine Bounou', position: 'GK', nation: 'Marrocos', club: 'Al Hilal', season: '2023/24', rarity: 'gold', overall: 85,
    pace: 37, shooting: 23, passing: 48, dribbling: 41, defending: 89, physical: 66, composure: 57, vision: 62, traits: [], photoUrl: '/players/fifaindex-versions/209981_24.webp' },
  { id: 'partey_arsenal_2022_23', shortName: 'Partey', fullName: 'Thomas Partey', position: 'CDM', nation: 'Gana', club: 'Arsenal', season: '2022/23', rarity: 'gold', overall: 85,
    pace: 69, shooting: 68, passing: 85, dribbling: 76, defending: 79, physical: 83, composure: 87, vision: 85, traits: [], photoUrl: '/players/fifaindex-versions/209989_23.webp' },
  { id: 'cancelo_al_hilal_2024_25', shortName: 'Cancelo', fullName: 'João Pedro Cavaco Cancelo', position: 'RB', nation: 'Portugal', club: 'Al Hilal', season: '2024/25', rarity: 'gold', overall: 85,
    pace: 82, shooting: 71, passing: 83, dribbling: 83, defending: 78, physical: 77, composure: 85, vision: 85, traits: [], photoUrl: '/players/fifaindex-versions/210514_25.webp' },
  { id: 'kante_al_ittihad_2023_24', shortName: 'Kanté', fullName: 'N\'Golo Kanté', position: 'CDM', nation: 'França', club: 'Al Ittihad', season: '2023/24', rarity: 'gold', overall: 85,
    pace: 69, shooting: 64, passing: 77, dribbling: 83, defending: 81, physical: 77, composure: 82, vision: 77, traits: [], photoUrl: '/players/fifaindex-versions/215914_24.webp' },
];
